Aq_excit – Fortran Program
Aq_excit Function
Source File
public function Aq_excit(eb, q, n_max, m_max) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
integer, intent(in) :: q
integer, intent(in) :: n_max
integer, intent(in) :: m_max
Return Value real(kind=Float64), dimension(n_max, m_max)
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=Float64), public, dimension(12,12) :: sigma_full
integer, public :: n
integer, public :: m
Call graph
aq_excit calls aq_excit_n
aq_excit_n calls aq_excit_2_janev, aq_excit_3_janev, aq_excit_1_janev, aq_excit_n_janev
aq_excit_2_janev calls aq_excit_2_10_janev, aq_excit_2_6_janev, aq_excit_2_8_janev, aq_excit_2_9_janev, aq_excit_2_5_janev, aq_excit_2_4_janev, aq_excit_2_3_janev, aq_excit_2_7_janev
aq_excit_3_janev calls aq_excit_3_4_janev, aq_excit_3_6_janev, aq_excit_3_10_janev, aq_excit_3_8_janev, aq_excit_3_9_janev, aq_excit_3_7_janev, aq_excit_3_5_janev
aq_excit_1_janev calls aq_excit_1_3_janev, aq_excit_1_4_janev, aq_excit_1_5_janev, aq_excit_1_2_janev
aq_excit_2_10_janev calls aq_excit_2_5_janev
aq_excit_2_6_janev calls aq_excit_2_5_janev
aq_excit_2_8_janev calls aq_excit_2_5_janev
aq_excit_2_9_janev calls aq_excit_2_5_janev
aq_excit_2_7_janev calls aq_excit_2_5_janev
aq_excit_3_10_janev calls aq_excit_3_6_janev
aq_excit_3_8_janev calls aq_excit_3_6_janev
aq_excit_3_9_janev calls aq_excit_3_6_janev
aq_excit_3_7_janev calls aq_excit_3_6_janev
write_bb_h_aq calls aq_excit
generate_tables calls write_bb_h_aq