bremsstrahlung – Fortran Program
bremsstrahlung Subroutine
Source File
public subroutine bremsstrahlung()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(LocalProfiles), public :: plasma
integer, public :: i
integer, public :: ichan
integer, public :: nc
integer, public :: ic
real(kind=double), public :: dlength
real(kind=double), public :: gaunt
real(kind=double), public :: max_length
real(kind=double), public :: spot_size
real(kind=double), public :: theta
real(kind=double), public :: sqrt_rho
real(kind=double), public, dimension(2) :: randomu
real(kind=double), public, dimension(3) :: vi
real(kind=double), public, dimension(3) :: xyz
real(kind=double), public, dimension(3) :: r0
real(kind=double), public, dimension(3,3) :: basis
real(kind=double), public, dimension(:), allocatable :: lambda_arr
real(kind=double), public, dimension(:), allocatable :: brems
Call graph
bremsstrahlung calls get_plasma, normp, randu, line_basis
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
randu calls rng_uniform, omp_get_thread_num
line_basis calls tb_zyx
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
fidasim calls bremsstrahlung