fida_f – Fortran Program
fida_f Subroutine
Source File
public subroutine fida_f()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: k
integer(kind=8), public :: iion
integer(kind=8), public :: ip
real(kind=double), public, dimension(3) :: ri
real(kind=double), public, dimension(3) :: vi
integer, public, dimension(3) :: ind
integer, public, dimension(4) :: neut_types = [1, 2, 3, 4]
logical, public :: los_intersect
type(LocalProfiles), public :: plasma
real(kind=double), public, dimension(nlevs) :: prob
integer, public :: ncell
integer, public :: jj
type(ParticleTrack), public, dimension(beam_grid%ntrack) :: tracks
real(kind=double), public :: photons
real(kind=double), public, dimension(nlevs) :: states
real(kind=double), public, dimension(nlevs) :: denn
integer(kind=8), public :: pcnt
real(kind=double), public :: papprox_tot
real(kind=double), public :: inv_maxcnt
real(kind=double), public :: cnt
integer, public, dimension(3,beam_grid%ngrid) :: pcell
real(kind=double), public, dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: papprox
real(kind=double), public, dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: nlaunch
Call graph
fida_f calls get_nlaunch, get_plasma, colrad, mc_fastion, track, store_fida_photons, get_beam_cx_prob
get_nlaunch calls randu
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
colrad calls matinv, get_rate_matrix, eigen
mc_fastion calls randu, get_fields, pitch_to_vec, gyro_correction, randind, get_distribution
track calls in_plasma, get_indices
store_fida_photons calls get_fields, get_indices, spectrum
get_beam_cx_prob calls normp, mc_halo, neut_rates
randu calls rng_uniform, omp_get_thread_num
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
matinv calls ludcmp, lubksb
get_rate_matrix calls interpol_coeff
eigen calls balance, elmtrans, elmhes, balback, hqr2
ludcmp calls swap, outerprod
balance calls rswap
elmhes calls rswap
balback calls rswap
hqr2 calls hqrvec
hqrvec calls comdiv
get_fields calls in_plasma, interpol_coeff, xyz_to_uvw, get_position, normp, calc_perp_vectors
gyro_correction calls cross_product
randind calls randind_w_2, randind_w_1, randind_n
get_distribution calls in_plasma, xyz_to_uvw, get_position, interpol
calc_perp_vectors calls normp
randind_w_2 calls randu, ind2sub
randind_w_1 calls randu
randind_n calls randu
spectrum calls normp
mc_halo calls get_plasma, randu, randn
neut_rates calls interpol_coeff, normp
randn calls omp_get_thread_num, rng_normal
rng_normal calls rng_uniform
fidasim calls fida_f