fida_mc – Fortran Program
fida_mc Subroutine
Source File
public subroutine fida_mc()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: iion
integer, public :: iphi
type(FastIon), public :: fast_ion
type(LocalEMFields), public :: fields
type(LocalProfiles), public :: plasma
real(kind=double), public :: phi
real(kind=double), public :: theta
real(kind=double), public, dimension(3) :: ri
real(kind=double), public, dimension(3) :: vi
real(kind=double), public, dimension(3) :: vi_norm
real(kind=double), public, dimension(nlevs) :: denn
real(kind=double), public, dimension(nlevs) :: prob
real(kind=double), public, dimension(nlevs) :: states
integer, public :: ncell
type(ParticleTrack), public, dimension(beam_grid%ntrack) :: tracks
logical, public :: los_intersect
integer, public :: jj
real(kind=double), public :: photons
integer, public, dimension(4) :: neut_types = [1, 2, 3, 4]
real(kind=double), public, dimension(3) :: xyz
real(kind=double), public, dimension(3) :: uvw
real(kind=double), public, dimension(3) :: r_gyro
real(kind=double), public, dimension(3) :: uvw_vi
real(kind=double), public :: s
real(kind=double), public :: c
real(kind=double), public :: maxcnt
real(kind=double), public :: inv_maxcnt
real(kind=double), public :: cnt
real(kind=double), public, dimension(2) :: randomu
integer(kind=long), public :: nlaunch
Call graph
fida_mc calls get_fields, uvw_to_xyz, get_plasma, colrad, pitch_to_vec, randu, track, gyro_correction, store_fida_photons, get_beam_cx_prob
get_fields calls in_plasma, interpol_coeff, normp, calc_perp_vectors, xyz_to_uvw, get_position
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
colrad calls matinv, get_rate_matrix, eigen
randu calls rng_uniform, omp_get_thread_num
track calls in_plasma, get_indices
gyro_correction calls cross_product
store_fida_photons calls get_fields, get_indices, spectrum
get_beam_cx_prob calls normp, mc_halo, neut_rates
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
calc_perp_vectors calls normp
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
matinv calls ludcmp, lubksb
get_rate_matrix calls interpol_coeff
eigen calls balance, elmtrans, elmhes, balback, hqr2
ludcmp calls swap, outerprod
balance calls rswap
elmhes calls rswap
balback calls rswap
hqr2 calls hqrvec
hqrvec calls comdiv
spectrum calls normp
mc_halo calls get_plasma, randu, randn
neut_rates calls interpol_coeff, normp
randn calls omp_get_thread_num, rng_normal
rng_normal calls rng_uniform
fidasim calls fida_mc