fida_weights_los – Fortran Program
fida_weights_los Subroutine
Source File
public subroutine fida_weights_los()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(LocalProfiles), public :: plasma
type(LocalProfiles), public :: plasma_cell
type(LocalEMFields), public :: fields
type(LocalEMFields), public :: fields_cell
real(kind=double), public :: denf
real(kind=double), public :: wght
real(kind=double), public :: wght_tot
real(kind=double), public :: photons
real(kind=double), public :: length
type(ParticleTrack), public, dimension(beam_grid%ntrack) :: tracks
integer, public :: nwav
integer(kind=long), public :: i
integer(kind=long), public :: j
integer(kind=long), public :: k
integer(kind=long), public :: ienergy
integer(kind=long), public :: ipitch
integer(kind=long), public :: igyro
integer(kind=long), public :: icell
integer(kind=long), public :: ichan
real(kind=double), public, dimension(:), allocatable :: ebarr
real(kind=double), public, dimension(:), allocatable :: ptcharr
real(kind=double), public, dimension(:), allocatable :: phiarr
real(kind=double), public, dimension(:,:), allocatable :: mean_f
real(kind=double), public, dimension(3) :: vi
real(kind=double), public, dimension(3) :: vi_norm
real(kind=double), public, dimension(3) :: vp
real(kind=double), public, dimension(3) :: vnbi_f
real(kind=double), public, dimension(3) :: vnbi_h
real(kind=double), public, dimension(3) :: vnbi_t
real(kind=double), public, dimension(3) :: vhalo
real(kind=double), public, dimension(3) :: r_enter
real(kind=double), public, dimension(3) :: r_exit
real(kind=double), public :: vabs
real(kind=double), public :: dE
real(kind=double), public :: dP
real(kind=double), public, dimension(nlevs) :: fdens
real(kind=double), public, dimension(nlevs) :: hdens
real(kind=double), public, dimension(nlevs) :: tdens
real(kind=double), public, dimension(nlevs) :: halodens
real(kind=double), public, dimension(nlevs) :: rates
real(kind=double), public, dimension(nlevs) :: states
real(kind=double), public, dimension(nlevs) :: denn
real(kind=double), public :: dt
real(kind=double), public :: max_dens
real(kind=double), public :: dlength
real(kind=double), public :: sigma_pi
real(kind=double), public :: eb
real(kind=double), public :: ptch
real(kind=double), public :: phi
integer, public, dimension(3) :: ind
real(kind=double), public, dimension(3) :: ri
integer(kind=long), public :: ncell
real(kind=double), public :: etov2
real(kind=double), public :: dEdP
Call graph
fida_weights_los calls store_fw_photons_at_chan, write_fida_weights, get_fields, get_plasma, colrad, get_ep_denf, pitch_to_vec, neut_rates, track, grid_intersect, normp, calc_perp_vectors, mc_halo
store_fw_photons_at_chan calls spectrum
write_fida_weights calls h5fcreate_f, h5ltmake_dataset_int_f, h5fclose_f, h5open_f, h5close_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f
get_fields calls normp, calc_perp_vectors, in_plasma, interpol_coeff, xyz_to_uvw, get_position
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
colrad calls matinv, get_rate_matrix, eigen
get_ep_denf calls in_plasma, xyz_to_uvw, get_position, interpol
neut_rates calls normp, interpol_coeff
track calls in_plasma, get_indices
calc_perp_vectors calls normp
mc_halo calls get_plasma, randu, randn
spectrum calls normp
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6
h5ltmake_compressed_dataset_double_f_4 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_7 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_3 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_1 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_2 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_5 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_6 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
matinv calls ludcmp, lubksb
get_rate_matrix calls interpol_coeff
eigen calls balance, elmtrans, elmhes, balback, hqr2
ludcmp calls swap, outerprod
balance calls rswap
elmhes calls rswap
balback calls rswap
hqr2 calls hqrvec
hqrvec calls comdiv
randu calls rng_uniform, omp_get_thread_num
randn calls omp_get_thread_num, rng_normal
rng_normal calls rng_uniform
fidasim calls fida_weights_los