fida_weights_mc – Fortran Program
fida_weights_mc Subroutine
Source File
public subroutine fida_weights_mc()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: k
integer(kind=8), public :: iion
integer(kind=8), public :: ip
real(kind=double), public, dimension(3) :: ri
real(kind=double), public, dimension(3) :: r_gyro
real(kind=double), public, dimension(3) :: vi
real(kind=double), public, dimension(3) :: vi_norm
integer, public, dimension(3) :: ind
integer, public, dimension(4) :: neut_types = [1, 2, 3, 4]
logical, public :: los_intersect
type(LocalProfiles), public :: plasma
type(LocalEMFields), public :: fields
real(kind=double), public, dimension(nlevs) :: prob
integer, public :: ncell
integer, public :: jj
integer, public :: kk
type(ParticleTrack), public, dimension(beam_grid%ntrack) :: tracks
real(kind=double), public :: photons
real(kind=double), public, dimension(nlevs) :: states
real(kind=double), public, dimension(nlevs) :: denn
integer, public :: nwav
real(kind=double), public :: etov2
real(kind=double), public :: energy
real(kind=double), public :: pitch
real(kind=double), public :: phi
real(kind=double), public :: dE
real(kind=double), public :: dP
real(kind=double), public :: dEdP
real(kind=double), public, dimension(:), allocatable :: ebarr
real(kind=double), public, dimension(:), allocatable :: ptcharr
integer, public, dimension(1) :: ienergy
integer, public, dimension(1) :: ipitch
real(kind=double), public, dimension(3) :: randomu3
integer(kind=8), public :: pcnt
real(kind=double), public :: papprox_tot
real(kind=double), public :: inv_maxcnt
real(kind=double), public :: cnt
real(kind=double), public :: fbm_denf
real(kind=double), public :: phase_area
integer, public, dimension(3,beam_grid%ngrid) :: pcell
real(kind=double), public, dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: papprox
real(kind=double), public, dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: nlaunch
Call graph
fida_weights_mc calls get_nlaunch, write_fida_weights, get_fields, get_plasma, colrad, get_ep_denf, pitch_to_vec, randu, track, gyro_correction, store_fw_photons, randind, get_beam_cx_prob
get_nlaunch calls randu
write_fida_weights calls h5fcreate_f, h5ltmake_dataset_int_f, h5fclose_f, h5open_f, h5close_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f
get_fields calls in_plasma, interpol_coeff, normp, calc_perp_vectors, xyz_to_uvw, get_position
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
colrad calls matinv, get_rate_matrix, eigen
get_ep_denf calls in_plasma, xyz_to_uvw, get_position, interpol
randu calls rng_uniform, omp_get_thread_num
track calls in_plasma, get_indices
gyro_correction calls cross_product
store_fw_photons calls get_fields, get_indices, store_fw_photons_at_chan
randind calls randind_w_2, randind_w_1, randind_n
get_beam_cx_prob calls normp, mc_halo, neut_rates
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6
h5ltmake_compressed_dataset_double_f_4 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_7 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_3 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_1 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_2 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_5 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_6 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
calc_perp_vectors calls normp
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
matinv calls ludcmp, lubksb
get_rate_matrix calls interpol_coeff
eigen calls balance, elmtrans, elmhes, balback, hqr2
ludcmp calls swap, outerprod
balance calls rswap
elmhes calls rswap
balback calls rswap
hqr2 calls hqrvec
hqrvec calls comdiv
store_fw_photons_at_chan calls spectrum
spectrum calls normp
randind_w_2 calls randu, ind2sub
randind_w_1 calls randu
randind_n calls randu
mc_halo calls get_plasma, randu, randn
neut_rates calls interpol_coeff, normp
randn calls omp_get_thread_num, rng_normal
rng_normal calls rng_uniform
fidasim calls fida_weights_mc