get_beam_cx_prob – Fortran Program
get_beam_cx_prob Subroutine
Source File
public subroutine get_beam_cx_prob(ind, pos, v_ion, types, prob)
Arguments
Type Intent Optional Attributes Name
integer(kind=long), intent(in), dimension(3) :: ind
real(kind=double), intent(in), dimension(3) :: pos
real(kind=double), intent(in), dimension(3) :: v_ion
integer(kind=long), intent(in), dimension(:) :: types
real(kind=double), intent(out), dimension(nlevs) :: prob
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: ntypes
integer, public :: i
integer, public :: ii
real(kind=double), public, dimension(nlevs) :: rates
real(kind=double), public, dimension(nlevs) :: denn
real(kind=double), public, dimension(3) :: vhalo
real(kind=double), public, dimension(3) :: vnbi
real(kind=double), public, dimension(3) :: vn
Call graph
get_beam_cx_prob calls normp, mc_halo, neut_rates
mc_halo calls get_plasma, randu, randn
neut_rates calls normp, interpol_coeff
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
randu calls rng_uniform, omp_get_thread_num
randn calls omp_get_thread_num, rng_normal
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
rng_normal calls rng_uniform
fida_mc calls get_beam_cx_prob
fida_f calls get_beam_cx_prob
halo calls get_beam_cx_prob
npa_f calls get_beam_cx_prob
npa_weights calls get_beam_cx_prob
fida_weights_mc calls get_beam_cx_prob
npa_mc calls get_beam_cx_prob
dcx calls get_beam_cx_prob
fidasim calls fida_mc, fida_f, halo, npa_f, npa_weights, fida_weights_mc, npa_mc, dcx