get_plasma – Fortran Program
get_plasma Subroutine
Source File
public subroutine get_plasma(plasma, pos, ind)
Arguments
Type Intent Optional Attributes Name
type(LocalProfiles), intent(out) :: plasma
real(kind=double), intent(in), optional dimension(3) :: pos
integer(kind=long), intent(in), optional dimension(3) :: ind
Calls
Called By
Variables
Type Visibility Attributes Name Initial
logical, public :: inp
real(kind=double), public, dimension(3) :: xyz
real(kind=double), public, dimension(3) :: uvw
real(kind=double), public, dimension(3) :: vrot_uvw
real(kind=double), public :: R
real(kind=double), public :: W
real(kind=double), public :: phi
real(kind=double), public :: s
real(kind=double), public :: c
real(kind=double), public :: b11
real(kind=double), public :: b12
real(kind=double), public :: b21
real(kind=double), public :: b22
integer, public :: i
integer, public :: j
Call graph
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
fida_weights_los calls get_plasma, mc_halo
fida_mc calls get_plasma, get_beam_cx_prob
fida_f calls get_plasma, get_beam_cx_prob
halo calls get_plasma, mc_halo, get_beam_cx_prob
bremsstrahlung calls get_plasma
npa_f calls get_plasma, attenuate, get_beam_cx_prob
ndmc calls get_plasma
attenuate calls get_plasma
fida_weights_mc calls get_plasma, get_beam_cx_prob
npa_mc calls get_plasma, attenuate, get_beam_cx_prob
dcx calls get_plasma, mc_halo, get_beam_cx_prob
mc_halo calls get_plasma
fidasim calls fida_weights_los, fida_mc, fida_f, halo, bremsstrahlung, npa_f, ndmc, fida_weights_mc, npa_mc, dcx, npa_weights
npa_weights calls attenuate, get_beam_cx_prob
get_beam_cx_prob calls mc_halo