get_indices – Fortran Program
get_indices Subroutine
Source File
public subroutine get_indices(pos, ind)
Arguments
Type Intent Optional Attributes Name
real(kind=double), intent(in), dimension(3) :: pos
integer(kind=long), intent(out), dimension(3) :: ind
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=double), public, dimension(3) :: mini
integer(kind=long), public, dimension(3) :: maxind
integer, public :: i
Call graph
store_bes_photons calls get_indices
track calls get_indices
store_fw_photons calls get_indices
store_fida_photons calls get_indices
npa_mc calls get_indices
halo calls store_bes_photons, track
dcx calls store_bes_photons, track
ndmc calls store_bes_photons, track
fidasim calls npa_mc, halo, dcx, ndmc, fida_weights_los, fida_mc, fida_f, read_chords, fida_weights_mc
fida_weights_los calls track
fida_mc calls track, store_fida_photons
fida_f calls track, store_fida_photons
read_chords calls track
fida_weights_mc calls track, store_fw_photons