get_rate_matrix – Fortran Program
get_rate_matrix Subroutine
Source File
public subroutine get_rate_matrix(plasma, i_type, eb, rmat)
Arguments
Type Intent Optional Attributes Name
type(LocalProfiles), intent(in) :: plasma
integer, intent(in) :: i_type
real(kind=double), intent(in) :: eb
real(kind=double), intent(out), dimension(nlevs,nlevs) :: rmat
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=double), public :: logEmin
real(kind=double), public :: dlogE
real(kind=double), public :: logeb
real(kind=double), public :: logTmin
real(kind=double), public :: dlogT
real(kind=double), public :: logti
real(kind=double), public :: logte
integer, public :: neb
integer, public :: nt
real(kind=double), public :: b11
real(kind=double), public :: b12
real(kind=double), public :: b21
real(kind=double), public :: b22
real(kind=double), public :: dene
real(kind=double), public :: denp
real(kind=double), public :: denimp
real(kind=double), public, dimension(nlevs,nlevs) :: H_H_pop
real(kind=double), public, dimension(nlevs,nlevs) :: H_e_pop
real(kind=double), public, dimension(nlevs,nlevs) :: H_Aq_pop
real(kind=double), public, dimension(nlevs) :: H_H_depop
real(kind=double), public, dimension(nlevs) :: H_e_depop
real(kind=double), public, dimension(nlevs) :: H_Aq_depop
integer, public :: ebi
integer, public :: tii
integer, public :: tei
integer, public :: n
integer, public :: err_status
Call graph
get_rate_matrix calls interpol_coeff
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
colrad calls get_rate_matrix
fida_weights_los calls colrad
fida_mc calls colrad
fida_f calls colrad
halo calls colrad
ndmc calls colrad
attenuate calls colrad
fida_weights_mc calls colrad
dcx calls colrad
fidasim calls fida_weights_los, fida_mc, fida_f, halo, ndmc, fida_weights_mc, dcx, npa_weights, npa_mc, npa_f
npa_weights calls attenuate
npa_mc calls attenuate
npa_f calls attenuate