get_position – Fortran Program
get_position Subroutine
Source File
public subroutine get_position(ind, pos)
Arguments
Type Intent Optional Attributes Name
integer(kind=long), intent(in), dimension(3) :: ind
real(kind=double), intent(out), dimension(3) :: pos
Called By
Call graph
get_plasma calls get_position
get_ep_denf calls get_position
get_fields calls get_position
get_distribution calls get_position
fida_weights_los calls get_plasma, get_ep_denf, get_fields, mc_halo
fida_mc calls get_plasma, get_fields, get_beam_cx_prob, store_fida_photons
fida_f calls get_plasma, get_beam_cx_prob, mc_fastion, store_fida_photons
halo calls get_plasma, mc_halo, get_beam_cx_prob, store_bes_photons
bremsstrahlung calls get_plasma
npa_f calls get_plasma, attenuate, get_beam_cx_prob, mc_fastion, store_npa
ndmc calls get_plasma, store_bes_photons
attenuate calls get_plasma
fida_weights_mc calls get_plasma, get_ep_denf, get_fields, get_beam_cx_prob, store_fw_photons
npa_mc calls get_plasma, get_fields, attenuate, get_beam_cx_prob, store_npa
dcx calls get_plasma, mc_halo, get_beam_cx_prob, store_bes_photons
mc_halo calls get_plasma
fidasim calls fida_weights_los, fida_mc, fida_f, halo, bremsstrahlung, npa_f, ndmc, fida_weights_mc, npa_mc, dcx, npa_weights
npa_weights calls get_ep_denf, get_fields, attenuate, get_beam_cx_prob
get_beam_cx_prob calls mc_halo
store_fw_photons calls get_fields
store_bes_photons calls get_fields
mc_fastion calls get_fields, get_distribution
store_npa calls get_fields
store_fida_photons calls get_fields