halo – Fortran Program
halo Subroutine
Source File
public subroutine halo()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: k
integer, public :: ihalo
real(kind=double), public, dimension(3) :: ri
real(kind=double), public, dimension(3) :: vihalo
integer, public, dimension(3) :: ind
type(LocalProfiles), public :: plasma
real(kind=double), public, dimension(nlevs) :: denn
real(kind=double), public, dimension(nlevs) :: prob
real(kind=double), public, dimension(nlevs) :: states
integer, public :: ncell
type(ParticleTrack), public, dimension(beam_grid%ntrack) :: tracks
integer, public :: jj
real(kind=double), public :: tot_denn
real(kind=double), public :: photons
real(kind=double), public, dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: papprox
real(kind=double), public, dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: nlaunch
real(kind=double), public :: papprox_tot
real(kind=double), public :: ccnt
real(kind=double), public :: inv_ng
integer, public :: hh
real(kind=double), public :: dcx_dens
real(kind=double), public :: halo_iteration_dens
integer, public :: s1type
integer, public :: s2type
Call graph
halo calls get_nlaunch, store_neutrals, get_plasma, colrad, store_bes_photons, track, get_beam_cx_prob, mc_halo
get_nlaunch calls randu
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
colrad calls matinv, get_rate_matrix, eigen
store_bes_photons calls get_indices, spectrum, get_fields
track calls in_plasma, get_indices
get_beam_cx_prob calls mc_halo, normp, neut_rates
mc_halo calls get_plasma, randu, randn
randu calls rng_uniform, omp_get_thread_num
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
matinv calls ludcmp, lubksb
get_rate_matrix calls interpol_coeff
eigen calls balance, elmtrans, elmhes, balback, hqr2
ludcmp calls swap, outerprod
balance calls rswap
elmhes calls rswap
balback calls rswap
hqr2 calls hqrvec
hqrvec calls comdiv
spectrum calls normp
get_fields calls in_plasma, interpol_coeff, xyz_to_uvw, get_position, normp, calc_perp_vectors
calc_perp_vectors calls normp
neut_rates calls interpol_coeff, normp
randn calls omp_get_thread_num, rng_normal
rng_normal calls rng_uniform
fidasim calls halo