hqrvec – Fortran Program
hqrvec Subroutine
Source File
public subroutine hqrvec(n, low, high, h, wr, wi, eivec, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: low
integer, intent(in) :: high
real(kind=double) :: h(0:n,0:n)
real(kind=double), intent(in) :: wr(0:n)
real(kind=double), intent(in) :: wi(0:n)
real(kind=double), intent(out) :: eivec(0:n,0:n)
integer :: rc
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: m
integer, public :: k
integer, public :: na
integer, public :: l
integer, public :: code
integer, public :: en
real(kind=double), public :: p
real(kind=double), public :: q
real(kind=double), public :: r
real(kind=double), public :: s
real(kind=double), public :: t
real(kind=double), public :: w
real(kind=double), public :: x
real(kind=double), public :: y
real(kind=double), public :: z
real(kind=double), public :: ra
real(kind=double), public :: sa
real(kind=double), public :: vr
real(kind=double), public :: vi
real(kind=double), public :: norm
real(kind=double), public :: temp
Call graph
hqrvec calls comdiv
hqr2 calls hqrvec
eigen calls hqr2
colrad calls eigen
fida_weights_los calls colrad
fida_mc calls colrad
fida_f calls colrad
halo calls colrad
ndmc calls colrad
attenuate calls colrad
fida_weights_mc calls colrad
dcx calls colrad
fidasim calls fida_weights_los, fida_mc, fida_f, halo, ndmc, fida_weights_mc, dcx, npa_weights, npa_mc, npa_f
npa_weights calls attenuate
npa_mc calls attenuate
npa_f calls attenuate