in_plasma – Fortran Program
in_plasma Subroutine
Source File
public subroutine in_plasma(xyz, inp)
Arguments
Type Intent Optional Attributes Name
real(kind=double), intent(in), dimension(3) :: xyz
logical, intent(out) :: inp
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=double), public, dimension(3) :: uvw
real(kind=double), public :: R
real(kind=double), public :: W
real(kind=double), public :: phi
real(kind=double), public :: mask
integer, public :: err
Call graph
in_plasma calls interpol, xyz_to_uvw
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
get_plasma calls in_plasma
track calls in_plasma
get_ep_denf calls in_plasma
get_fields calls in_plasma
get_distribution calls in_plasma
fida_weights_los calls get_plasma, track, get_ep_denf, get_fields, mc_halo
fida_mc calls get_plasma, track, get_fields, get_beam_cx_prob, store_fida_photons
fida_f calls get_plasma, track, get_beam_cx_prob, mc_fastion, store_fida_photons
halo calls get_plasma, track, mc_halo, get_beam_cx_prob, store_bes_photons
bremsstrahlung calls get_plasma
npa_f calls get_plasma, attenuate, get_beam_cx_prob, mc_fastion, store_npa
ndmc calls get_plasma, track, store_bes_photons
attenuate calls get_plasma
fida_weights_mc calls get_plasma, track, get_ep_denf, get_fields, get_beam_cx_prob, store_fw_photons
npa_mc calls get_plasma, get_fields, attenuate, get_beam_cx_prob, store_npa
dcx calls get_plasma, track, mc_halo, get_beam_cx_prob, store_bes_photons
mc_halo calls get_plasma
fidasim calls fida_weights_los, fida_mc, fida_f, halo, bremsstrahlung, npa_f, ndmc, fida_weights_mc, npa_mc, dcx, npa_weights, read_chords
npa_weights calls get_ep_denf, get_fields, attenuate, get_beam_cx_prob
get_beam_cx_prob calls mc_halo
read_chords calls track
store_fw_photons calls get_fields
store_bes_photons calls get_fields
mc_fastion calls get_fields, get_distribution
store_npa calls get_fields
store_fida_photons calls get_fields