interpol1D_coeff_arr – Fortran Program
interpol1D_coeff_arr Subroutine
Source File
public subroutine interpol1D_coeff_arr(x, xout, i, b1, b2, err)
Arguments
Type Intent Optional Attributes Name
real(kind=double), intent(in), dimension(:) :: x
real(kind=double), intent(in) :: xout
integer, intent(out) :: i
real(kind=double), intent(out) :: b1
real(kind=double), intent(out) :: b2
integer, intent(out), optional :: err
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=double), public :: xmin
real(kind=double), public :: dx
integer, public :: sx
integer, public :: err_status
Call graph
interpol1d_coeff_arr calls interpol1d_coeff
interpol_coeff calls interpol1d_coeff_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
get_fields calls interpol_coeff, in_plasma
get_plasma calls interpol_coeff, in_plasma
neut_rates calls interpol_coeff
get_rate_matrix calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
in_plasma calls interpol
get_ep_denf calls interpol, in_plasma
get_distribution calls interpol, in_plasma
track calls in_plasma
fida_weights_los calls get_fields, get_plasma, neut_rates, get_ep_denf, track, mc_halo, colrad
fida_mc calls get_fields, get_plasma, track, store_fida_photons, get_beam_cx_prob, colrad
fida_f calls get_plasma, track, mc_fastion, store_fida_photons, get_beam_cx_prob, colrad
halo calls get_plasma, track, store_bes_photons, mc_halo, get_beam_cx_prob, colrad
read_chords calls track
ndmc calls get_plasma, track, store_bes_photons, colrad
fida_weights_mc calls get_fields, get_plasma, get_ep_denf, track, store_fw_photons, get_beam_cx_prob, colrad
dcx calls get_plasma, track, store_bes_photons, mc_halo, get_beam_cx_prob, colrad
fidasim calls fida_weights_los, fida_mc, fida_f, halo, read_chords, ndmc, fida_weights_mc, dcx, npa_weights, npa_f, npa_mc, bremsstrahlung
npa_weights calls get_fields, get_ep_denf, attenuate, get_beam_cx_prob
mc_fastion calls get_fields, get_distribution
npa_f calls get_plasma, mc_fastion, store_npa, attenuate, get_beam_cx_prob
store_fw_photons calls get_fields
store_bes_photons calls get_fields
store_npa calls get_fields
store_fida_photons calls get_fields
npa_mc calls get_fields, get_plasma, store_npa, attenuate, get_beam_cx_prob
bremsstrahlung calls get_plasma
attenuate calls get_plasma, colrad
mc_halo calls get_plasma
get_beam_cx_prob calls neut_rates, mc_halo
colrad calls get_rate_matrix