interpol1D_arr – Fortran Program
interpol1D_arr Subroutine
Source File
public subroutine interpol1D_arr(x, y, xout, yout, err)
Arguments
Type Intent Optional Attributes Name
real(kind=double), intent(in), dimension(:) :: x
real(kind=double), intent(in), dimension(:) :: y
real(kind=double), intent(in) :: xout
real(kind=double), intent(out) :: yout
integer, intent(out), optional :: err
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=double), public :: b1
real(kind=double), public :: b2
integer, public :: i
integer, public :: err_status
Call graph
interpol1d_arr calls interpol_coeff
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
interpol calls interpol1d_arr
in_plasma calls interpol
get_ep_denf calls interpol, in_plasma
get_distribution calls interpol, in_plasma
get_plasma calls in_plasma
track calls in_plasma
get_fields calls in_plasma
fida_weights_los calls get_ep_denf, get_plasma, track, get_fields, mc_halo
fida_mc calls get_plasma, track, get_fields, get_beam_cx_prob, store_fida_photons
fida_f calls get_plasma, track, get_beam_cx_prob, mc_fastion, store_fida_photons
halo calls get_plasma, track, mc_halo, get_beam_cx_prob, store_bes_photons
bremsstrahlung calls get_plasma
npa_f calls get_plasma, attenuate, get_beam_cx_prob, mc_fastion, store_npa
ndmc calls get_plasma, track, store_bes_photons
attenuate calls get_plasma
fida_weights_mc calls get_ep_denf, get_plasma, track, get_fields, get_beam_cx_prob, store_fw_photons
npa_mc calls get_plasma, get_fields, attenuate, get_beam_cx_prob, store_npa
dcx calls get_plasma, track, mc_halo, get_beam_cx_prob, store_bes_photons
mc_halo calls get_plasma
fidasim calls fida_weights_los, fida_mc, fida_f, halo, bremsstrahlung, npa_f, ndmc, fida_weights_mc, npa_mc, dcx, npa_weights, read_chords
npa_weights calls get_ep_denf, get_fields, attenuate, get_beam_cx_prob
get_beam_cx_prob calls mc_halo
read_chords calls track
store_fw_photons calls get_fields
store_bes_photons calls get_fields
mc_fastion calls get_distribution, get_fields
store_npa calls get_fields
store_fida_photons calls get_fields