mc_fastion – Fortran Program
mc_fastion Subroutine
Source File
public subroutine mc_fastion(ind, ri, vi, at_guiding_center)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(3) :: ind
real(kind=double), intent(out), dimension(3) :: ri
real(kind=double), intent(out), dimension(3) :: vi
logical, intent(in), optional :: at_guiding_center
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(LocalEMFields), public :: fields
real(kind=double), public, dimension(fbm%nenergy,fbm%npitch) :: fbeam
real(kind=double), public, dimension(3) :: r_gyro
real(kind=double), public, dimension(3) :: rp
real(kind=double), public :: eb
real(kind=double), public :: ptch
integer, public :: ii
integer, public :: ienergy
integer, public :: ipitch
real(kind=double), public :: vabs
real(kind=double), public :: phi
real(kind=double), public, dimension(3) :: randomu3
real(kind=double), public, dimension(4) :: randomu4
integer, public, dimension(1) :: minpos
integer, public, dimension(2,1) :: ep_ind
real(kind=double), public, dimension(1) :: max_fbm
logical, public :: use_inverse_sampler
Call graph
mc_fastion calls get_fields, pitch_to_vec, randu, gyro_correction, randind, get_distribution
get_fields calls in_plasma, interpol_coeff, normp, calc_perp_vectors, xyz_to_uvw, get_position
randu calls rng_uniform, omp_get_thread_num
gyro_correction calls cross_product
randind calls randind_w_2, randind_w_1, randind_n
get_distribution calls in_plasma, xyz_to_uvw, get_position, interpol
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
calc_perp_vectors calls normp
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
randind_w_2 calls randu, ind2sub
randind_w_1 calls randu
randind_n calls randu
fida_f calls mc_fastion
npa_f calls mc_fastion
fidasim calls fida_f, npa_f