mc_halo – Fortran Program
mc_halo Subroutine
Source File
public subroutine mc_halo(ind, vhalo, ri, plasma_in)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(3) :: ind
real(kind=double), intent(out), dimension(3) :: vhalo
real(kind=double), intent(out), optional dimension(3) :: ri
type(LocalProfiles), intent(in), optional :: plasma_in
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(LocalProfiles), public :: plasma
real(kind=double), public, dimension(3) :: random3
Call graph
mc_halo calls get_plasma, randu, randn
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
randu calls rng_uniform, omp_get_thread_num
randn calls omp_get_thread_num, rng_normal
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
rng_normal calls rng_uniform
fida_weights_los calls mc_halo
get_beam_cx_prob calls mc_halo
halo calls mc_halo, get_beam_cx_prob
dcx calls mc_halo, get_beam_cx_prob
fidasim calls fida_weights_los, halo, dcx, fida_mc, fida_f, npa_f, npa_weights, fida_weights_mc, npa_mc
fida_mc calls get_beam_cx_prob
fida_f calls get_beam_cx_prob
npa_f calls get_beam_cx_prob
npa_weights calls get_beam_cx_prob
fida_weights_mc calls get_beam_cx_prob
npa_mc calls get_beam_cx_prob