ndmc – Fortran Program
ndmc Subroutine
Source File
public subroutine ndmc()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: neut_type
real(kind=double), public :: nlaunch
real(kind=double), public :: nneutrals
real(kind=double), public, dimension(3) :: vnbi
real(kind=double), public, dimension(3) :: rnbi
integer, public :: jj
integer, public :: ii
integer, public :: kk
integer, public :: ncell
type(ParticleTrack), public, dimension(beam_grid%ntrack) :: tracks
integer, public, dimension(3) :: nl_birth
type(LocalProfiles), public :: plasma
real(kind=double), public, dimension(nlevs) :: states
real(kind=double), public, dimension(nlevs) :: dens
real(kind=double), public :: photons
real(kind=double), public :: iflux
integer(kind=long), public, dimension(3) :: ind
real(kind=double), public, dimension(1) :: randomu
integer, public, dimension(1) :: randi
Call graph
ndmc calls store_neutrals, get_plasma, colrad, store_bes_photons, track, store_births, mc_nbi, randu, randind
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
colrad calls matinv, get_rate_matrix, eigen
store_bes_photons calls get_indices, spectrum, get_fields
track calls in_plasma, get_indices
mc_nbi calls randu, normp, grid_intersect, randn
randu calls omp_get_thread_num, rng_uniform
randind calls randind_w_2, randind_w_1, randind_n
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
matinv calls ludcmp, lubksb
get_rate_matrix calls interpol_coeff
eigen calls balance, elmtrans, elmhes, balback, hqr2
ludcmp calls swap, outerprod
balance calls rswap
elmhes calls rswap
balback calls rswap
hqr2 calls hqrvec
hqrvec calls comdiv
spectrum calls normp
get_fields calls in_plasma, interpol_coeff, xyz_to_uvw, get_position, normp, calc_perp_vectors
calc_perp_vectors calls normp
randn calls rng_normal, omp_get_thread_num
rng_normal calls rng_uniform
randind_w_2 calls randu, ind2sub
randind_w_1 calls randu
randind_n calls randu
fidasim calls ndmc