normp – Fortran Program
normp Function
Source File
public function normp(u, p_in) result(n)
Arguments
Type Intent Optional Attributes Name
real(kind=double), intent(in), dimension(:) :: u
integer, intent(in), optional :: p_in
Return Value real(kind=double)
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: p
Call graph
fida_weights_los calls normp, get_fields, neut_rates, calc_perp_vectors, store_fw_photons_at_chan
get_fields calls normp, calc_perp_vectors
npa_weights calls normp, get_fields, attenuate, get_beam_cx_prob
attenuate calls normp
bremsstrahlung calls normp
neut_rates calls normp
read_chords calls normp
spectrum calls normp
plane_basis calls normp
mc_nbi calls normp
read_rates calls normp
store_npa calls normp, get_fields
calc_perp_vectors calls normp
read_npa calls normp, plane_basis
get_beam_cx_prob calls normp, neut_rates
fidasim calls fida_weights_los, npa_weights, bremsstrahlung, read_chords, read_npa, fida_mc, fida_weights_mc, npa_mc, halo, dcx, ndmc, fida_f, npa_f, read_tables
store_fw_photons calls get_fields, store_fw_photons_at_chan
fida_mc calls get_fields, get_beam_cx_prob, store_fida_photons
store_bes_photons calls get_fields, spectrum
mc_fastion calls get_fields
store_fida_photons calls get_fields, spectrum
fida_weights_mc calls get_fields, get_beam_cx_prob, store_fw_photons
npa_mc calls get_fields, attenuate, store_npa, get_beam_cx_prob
halo calls get_beam_cx_prob, store_bes_photons
dcx calls get_beam_cx_prob, store_bes_photons
ndmc calls mc_nbi, store_bes_photons
fida_f calls get_beam_cx_prob, mc_fastion, store_fida_photons
npa_f calls attenuate, store_npa, get_beam_cx_prob, mc_fastion
store_fw_photons_at_chan calls spectrum
read_tables calls read_rates