npa_f – Fortran Program
npa_f Subroutine
Source File
public subroutine npa_f()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: k
integer, public :: iion
integer, public :: det
integer, public :: ip
real(kind=double), public, dimension(3) :: ri
real(kind=double), public, dimension(3) :: rf
real(kind=double), public, dimension(3) :: vi
integer, public, dimension(3) :: ind
integer, public, dimension(3,beam_grid%ngrid) :: pcell
type(LocalProfiles), public :: plasma
integer, public, dimension(4) :: neut_types = [1, 2, 3, 4]
real(kind=double), public, dimension(nlevs) :: prob
real(kind=double), public, dimension(nlevs) :: states
real(kind=double), public :: flux
integer, public :: inpa
integer, public :: pcnt
real(kind=double), public :: papprox_tot
real(kind=double), public :: maxcnt
real(kind=double), public :: cnt
real(kind=double), public :: inv_maxcnt
real(kind=double), public, dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: papprox
real(kind=double), public, dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: nlaunch
Call graph
npa_f calls get_nlaunch, get_plasma, mc_fastion, store_npa, attenuate, get_beam_cx_prob, hit_npa_detector
get_nlaunch calls randu
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
mc_fastion calls randu, get_fields, pitch_to_vec, gyro_correction, randind, get_distribution
store_npa calls xyz_to_uvw, get_fields, normp
attenuate calls get_plasma, normp, colrad
get_beam_cx_prob calls normp, mc_halo, neut_rates
hit_npa_detector calls in_boundary, plane_intercept
randu calls rng_uniform, omp_get_thread_num
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
get_fields calls in_plasma, interpol_coeff, xyz_to_uvw, get_position, normp, calc_perp_vectors
gyro_correction calls cross_product
randind calls randind_w_2, randind_w_1, randind_n
get_distribution calls in_plasma, xyz_to_uvw, get_position, interpol
calc_perp_vectors calls normp
randind_w_2 calls randu, ind2sub
randind_w_1 calls randu
randind_n calls randu
colrad calls matinv, get_rate_matrix, eigen
matinv calls ludcmp, lubksb
get_rate_matrix calls interpol_coeff
eigen calls balance, elmtrans, elmhes, balback, hqr2
ludcmp calls swap, outerprod
balance calls rswap
elmhes calls rswap
balback calls rswap
hqr2 calls hqrvec
hqrvec calls comdiv
mc_halo calls get_plasma, randu, randn
neut_rates calls interpol_coeff, normp
randn calls omp_get_thread_num, rng_normal
rng_normal calls rng_uniform
fidasim calls npa_f