npa_mc – Fortran Program
npa_mc Subroutine
Source File
public subroutine npa_mc()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: iion
integer, public :: iphi
type(FastIon), public :: fast_ion
type(LocalEMFields), public :: fields
type(LocalProfiles), public :: plasma
real(kind=double), public :: phi
real(kind=double), public :: theta
real(kind=double), public, dimension(3) :: ri
real(kind=double), public, dimension(3) :: rf
real(kind=double), public, dimension(3) :: vi
real(kind=double), public, dimension(3) :: vi_norm
integer, public :: det
real(kind=double), public, dimension(nlevs) :: prob
real(kind=double), public, dimension(nlevs) :: states
real(kind=double), public :: flux
integer, public, dimension(4) :: neut_types = [1, 2, 3, 4]
integer, public, dimension(3) :: ind
real(kind=double), public, dimension(3) :: xyz
real(kind=double), public, dimension(3) :: uvw
real(kind=double), public, dimension(3) :: r_gyro
real(kind=double), public, dimension(3) :: uvw_vi
real(kind=double), public :: s
real(kind=double), public :: c
real(kind=double), public :: maxcnt
real(kind=double), public :: inv_maxcnt
real(kind=double), public :: cnt
real(kind=double), public, dimension(2) :: randomu
integer(kind=long), public :: nlaunch
Call graph
npa_mc calls store_npa, get_fields, uvw_to_xyz, get_plasma, pitch_to_vec, randu, gyro_correction, get_indices, attenuate, get_beam_cx_prob, hit_npa_detector
store_npa calls get_fields, normp, xyz_to_uvw
get_fields calls normp, xyz_to_uvw, in_plasma, interpol_coeff, calc_perp_vectors, get_position
get_plasma calls xyz_to_uvw, in_plasma, interpol_coeff, get_position
randu calls rng_uniform, omp_get_thread_num
gyro_correction calls cross_product
attenuate calls get_plasma, normp, colrad
get_beam_cx_prob calls normp, mc_halo, neut_rates
hit_npa_detector calls in_boundary, plane_intercept
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
calc_perp_vectors calls normp
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
colrad calls matinv, get_rate_matrix, eigen
matinv calls ludcmp, lubksb
get_rate_matrix calls interpol_coeff
eigen calls balance, elmtrans, elmhes, balback, hqr2
ludcmp calls swap, outerprod
balance calls rswap
elmhes calls rswap
balback calls rswap
hqr2 calls hqrvec
hqrvec calls comdiv
mc_halo calls get_plasma, randu, randn
neut_rates calls normp, interpol_coeff
randn calls omp_get_thread_num, rng_normal
rng_normal calls rng_uniform
fidasim calls npa_mc