npa_weights – Fortran Program
npa_weights Subroutine
Source File
public subroutine npa_weights()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(LocalEMFields), public :: fields
real(kind=double), public :: pitch
real(kind=double), public :: pcxa
integer(kind=long), public :: det
integer(kind=long), public :: ii
integer(kind=long), public :: jj
integer(kind=long), public :: kk
integer(kind=long), public :: i
integer(kind=long), public :: ic
integer, public, dimension(1) :: ipitch
real(kind=double), public, dimension(3) :: vi
real(kind=double), public, dimension(3) :: vi_norm
real(kind=double), public :: vabs
real(kind=double), public :: fbm_denf
real(kind=double), public :: dE
real(kind=double), public :: dP
real(kind=double), public :: ccnt
real(kind=double), public, dimension(nlevs) :: pcx
real(kind=double), public, dimension(nlevs) :: states
real(kind=double), public, dimension(nlevs) :: states_i
integer, public, dimension(4) :: neut_types = [1, 2, 3, 4]
real(kind=double), public, dimension(3) :: pos
real(kind=double), public, dimension(3) :: dpos
real(kind=double), public, dimension(3) :: r_gyro
integer(kind=long), public :: ichan
real(kind=double), public, dimension(:), allocatable :: ebarr
real(kind=double), public, dimension(:), allocatable :: ptcharr
Call graph
npa_weights calls get_fields, attenuate, get_ep_denf, write_npa_weights, gyro_correction, normp, get_beam_cx_prob, hit_npa_detector
get_fields calls normp, in_plasma, interpol_coeff, calc_perp_vectors, xyz_to_uvw, get_position
attenuate calls normp, get_plasma, colrad
get_ep_denf calls in_plasma, xyz_to_uvw, get_position, interpol
write_npa_weights calls h5fcreate_f, h5ltmake_dataset_int_f, h5fclose_f, h5open_f, h5close_f, h5ltmake_compressed_dataset_double_f, write_beam_grid, h5ltset_attribute_string_f
gyro_correction calls cross_product
get_beam_cx_prob calls normp, mc_halo, neut_rates
hit_npa_detector calls in_boundary, plane_intercept
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
calc_perp_vectors calls normp
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
colrad calls matinv, get_rate_matrix, eigen
matinv calls ludcmp, lubksb
get_rate_matrix calls interpol_coeff
eigen calls balance, elmtrans, elmhes, balback, hqr2
ludcmp calls swap, outerprod
balance calls rswap
elmhes calls rswap
balback calls rswap
hqr2 calls hqrvec
hqrvec calls comdiv
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6
write_beam_grid calls xyz_to_uvw, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, h5gcreate_f, h5gclose_f
h5ltmake_compressed_dataset_double_f_4 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_7 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_3 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_1 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_2 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_5 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_6 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
mc_halo calls get_plasma, randu, randn
neut_rates calls normp, interpol_coeff
randu calls rng_uniform, omp_get_thread_num
randn calls omp_get_thread_num, rng_normal
rng_normal calls rng_uniform
fidasim calls npa_weights