p_cx – Fortran Program
p_cx Function
Source File
public function p_cx(Erel, n_max, m_max) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: Erel
integer, intent(in) :: n_max
integer, intent(in) :: m_max
Return Value real(kind=Float64), dimension(m_max,n_max)
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=Float64), public, dimension(12,12) :: sigma_full
integer, public :: n
integer, public :: m
Call graph
p_cx calls p_cx_n
p_cx_n calls p_cx_2, p_cx_janev, p_cx_1_4_adas, p_cx_3_4_adas, p_cx_3_5_adas, p_cx_1, m_spread, p_cx_3
p_cx_2 calls p_cx_janev, m_spread, p_cx_1_2_adas, p_cx_2_2_adas, p_cx_2_3_adas
p_cx_janev calls p_cx_2_janev, p_cx_4_janev, p_cx_3_janev, p_cx_1_janev
p_cx_1 calls p_cx_janev, p_cx_1_4_adas, p_cx_1_2_adas, p_cx_1_3_adas, p_cx_1_1_adas
p_cx_3 calls p_cx_janev, p_cx_3_4_adas, p_cx_3_5_adas, p_cx_1, m_spread, p_cx_1_3_adas, p_cx_3_3_adas, p_cx_3_6inf_adas, p_cx_3_2_adas
write_bb_h_h calls p_cx
generate_tables calls write_bb_h_h