p_cx_n_m – Fortran Program
p_cx_n_m Function
Source File
public function p_cx_n_m(Erel, n, m) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: Erel
integer, intent(in) :: n
integer, intent(in) :: m
Return Value real(kind=Float64)
Calls
Variables
Type Visibility Attributes Name Initial
integer, public :: m_max = 12
real(kind=Float64), public, dimension(12) :: sigma_m
Call graph
p_cx_n_m calls p_cx_n
p_cx_n calls p_cx_2, p_cx_janev, p_cx_1_4_adas, p_cx_3_4_adas, p_cx_3_5_adas, p_cx_1, m_spread, p_cx_3
p_cx_2 calls p_cx_janev, m_spread, p_cx_1_2_adas, p_cx_2_2_adas, p_cx_2_3_adas
p_cx_janev calls p_cx_2_janev, p_cx_4_janev, p_cx_3_janev, p_cx_1_janev
p_cx_1 calls p_cx_janev, p_cx_1_4_adas, p_cx_1_2_adas, p_cx_1_3_adas, p_cx_1_1_adas
p_cx_3 calls p_cx_janev, p_cx_3_4_adas, p_cx_3_5_adas, p_cx_1, m_spread, p_cx_1_3_adas, p_cx_3_3_adas, p_cx_3_6inf_adas, p_cx_3_2_adas