p_excit_n – Fortran Program
p_excit_n Function
Source File
public function p_excit_n(eb, n, m_max) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
integer, intent(in) :: n
integer, intent(in) :: m_max
Return Value real(kind=Float64), dimension(m_max)
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: m
real(kind=Float64), public :: nf
real(kind=Float64), public :: mf
real(kind=Float64), public :: Etil
real(kind=Float64), public :: s
real(kind=Float64), public :: D
real(kind=Float64), public :: A
real(kind=Float64), public :: G
real(kind=Float64), public :: L
real(kind=Float64), public :: F
real(kind=Float64), public :: y
real(kind=Float64), public :: zpl
real(kind=Float64), public :: zmi
real(kind=Float64), public :: C2pl
real(kind=Float64), public :: C2mi
real(kind=Float64), public :: H
Call graph
p_excit_n calls p_excit_2_janev, p_excit_3_janev, p_excit_1_janev
p_excit_2_janev calls p_excit_2_5_janev, p_excit_2_8_janev, p_excit_2_3_janev, p_excit_2_7_janev, p_excit_2_10_janev, p_excit_2_4_janev, p_excit_2_6_janev, p_excit_2_9_janev
p_excit_3_janev calls p_excit_3_10_janev, p_excit_3_4_janev, p_excit_3_9_janev, p_excit_3_7_janev, p_excit_3_6_janev, p_excit_3_8_janev, p_excit_3_5_janev
p_excit_1_janev calls p_excit_1_5_janev, p_excit_1_4_janev, p_excit_1_2_janev, p_excit_1_3_janev, p_excit_1_6_janev
p_excit_2_8_janev calls p_excit_2_5_janev
p_excit_2_7_janev calls p_excit_2_5_janev
p_excit_2_10_janev calls p_excit_2_5_janev
p_excit_2_6_janev calls p_excit_2_5_janev
p_excit_2_9_janev calls p_excit_2_5_janev
p_excit_3_10_janev calls p_excit_3_6_janev
p_excit_3_9_janev calls p_excit_3_6_janev
p_excit_3_7_janev calls p_excit_3_6_janev
p_excit_3_8_janev calls p_excit_3_6_janev
p_excit calls p_excit_n
p_excit_n_m calls p_excit_n
write_bb_h_h calls p_excit
generate_tables calls write_bb_h_h