p_excit – Fortran Program
p_excit Function
Source File
public function p_excit(eb, n_max, m_max) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
integer, intent(in) :: n_max
integer, intent(in) :: m_max
Return Value real(kind=Float64), dimension(m_max,n_max)
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=Float64), public, dimension(12,12) :: sigma_full
integer, public :: n
integer, public :: m
Call graph
p_excit calls p_excit_n
p_excit_n calls p_excit_2_janev, p_excit_3_janev, p_excit_1_janev
p_excit_2_janev calls p_excit_2_5_janev, p_excit_2_8_janev, p_excit_2_3_janev, p_excit_2_7_janev, p_excit_2_10_janev, p_excit_2_4_janev, p_excit_2_6_janev, p_excit_2_9_janev
p_excit_3_janev calls p_excit_3_10_janev, p_excit_3_4_janev, p_excit_3_9_janev, p_excit_3_7_janev, p_excit_3_6_janev, p_excit_3_8_janev, p_excit_3_5_janev
p_excit_1_janev calls p_excit_1_5_janev, p_excit_1_4_janev, p_excit_1_2_janev, p_excit_1_3_janev, p_excit_1_6_janev
p_excit_2_8_janev calls p_excit_2_5_janev
p_excit_2_7_janev calls p_excit_2_5_janev
p_excit_2_10_janev calls p_excit_2_5_janev
p_excit_2_6_janev calls p_excit_2_5_janev
p_excit_2_9_janev calls p_excit_2_5_janev
p_excit_3_10_janev calls p_excit_3_6_janev
p_excit_3_9_janev calls p_excit_3_6_janev
p_excit_3_7_janev calls p_excit_3_6_janev
p_excit_3_8_janev calls p_excit_3_6_janev
write_bb_h_h calls p_excit
generate_tables calls write_bb_h_h