p_excit_n_m – Fortran Program
p_excit_n_m Function
Source File
public function p_excit_n_m(eb, n, m) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
integer, intent(in) :: n
integer, intent(in) :: m
Return Value real(kind=Float64)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=Float64), public, dimension(12) :: sigma_m
Call graph
p_excit_n_m calls p_excit_n
p_excit_n calls p_excit_2_janev, p_excit_3_janev, p_excit_1_janev
p_excit_2_janev calls p_excit_2_5_janev, p_excit_2_8_janev, p_excit_2_3_janev, p_excit_2_7_janev, p_excit_2_10_janev, p_excit_2_4_janev, p_excit_2_6_janev, p_excit_2_9_janev
p_excit_3_janev calls p_excit_3_10_janev, p_excit_3_4_janev, p_excit_3_9_janev, p_excit_3_7_janev, p_excit_3_6_janev, p_excit_3_8_janev, p_excit_3_5_janev
p_excit_1_janev calls p_excit_1_5_janev, p_excit_1_4_janev, p_excit_1_2_janev, p_excit_1_3_janev, p_excit_1_6_janev
p_excit_2_8_janev calls p_excit_2_5_janev
p_excit_2_7_janev calls p_excit_2_5_janev
p_excit_2_10_janev calls p_excit_2_5_janev
p_excit_2_6_janev calls p_excit_2_5_janev
p_excit_2_9_janev calls p_excit_2_5_janev
p_excit_3_10_janev calls p_excit_3_6_janev
p_excit_3_9_janev calls p_excit_3_6_janev
p_excit_3_7_janev calls p_excit_3_6_janev
p_excit_3_8_janev calls p_excit_3_6_janev