randu – Fortran Program
randu Subroutine
Source File
public subroutine randu(randomu)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(out), dimension(:) :: randomu
Array of uniform random deviates
Description
Generate an array of uniformally-distributed random deviates
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: thread_id
Call graph
randu calls rng_uniform, omp_get_thread_num
randind_w_2 calls randu
get_nlaunch calls randu
fida_mc calls randu, get_beam_cx_prob
randind_w_1 calls randu
mc_fastion calls randu, randind
randind_n calls randu
bremsstrahlung calls randu
read_chords calls randu
mc_nbi calls randu
ndmc calls randu, mc_nbi, randind
fida_weights_mc calls randu, get_nlaunch, randind, get_beam_cx_prob
npa_mc calls randu, get_beam_cx_prob
mc_halo calls randu
randind calls randind_w_2, randind_w_1, randind_n
fida_f calls get_nlaunch, mc_fastion, get_beam_cx_prob
halo calls get_nlaunch, mc_halo, get_beam_cx_prob
dcx calls get_nlaunch, mc_halo, get_beam_cx_prob
npa_f calls get_nlaunch, mc_fastion, get_beam_cx_prob
fidasim calls fida_mc, bremsstrahlung, read_chords, ndmc, fida_weights_mc, npa_mc, fida_f, halo, dcx, npa_f, fida_weights_los, npa_weights
fida_weights_los calls mc_halo
get_beam_cx_prob calls mc_halo
npa_weights calls get_beam_cx_prob