read_tables – Fortran Program
read_tables Subroutine
Source File
public subroutine read_tables()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=HID_T), public :: fid
integer(kind=HSIZE_T), public, dimension(2) :: dim2
integer, public :: error
integer, public :: n_max
integer, public :: m_max
character(len=4), public :: impname
real(kind=double), public :: imp_amu
real(kind=double), public, dimension(2) :: b_amu
real(kind=double), public, dimension(:,:), allocatable :: dummy2
Call graph
read_tables calls read_cross, h5fclose_f, h5open_f, h5close_f, h5ltread_dataset_int_scalar_f, h5fopen_f, read_rates, h5ltread_dataset_double_f
read_cross calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5ltread_dataset_double_scalar_f
h5ltread_dataset_int_scalar_f calls h5ltread_dataset_int_f
read_rates calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5ltread_dataset_double_scalar_f, h5ltpath_valid_f, h5ltget_dataset_ndims_f, normp
h5ltread_dataset_double_scalar_f calls h5ltread_dataset_double_f
fidasim calls read_tables