read_npa – Fortran Program
read_npa Subroutine
Source File
public subroutine read_npa()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=HID_T), public :: fid
integer(kind=HID_T), public :: gid
integer(kind=HSIZE_T), public, dimension(2) :: dims
logical, public :: path_valid
real(kind=double), public, dimension(:,:), allocatable :: a_tedge
real(kind=double), public, dimension(:,:), allocatable :: a_redge
real(kind=double), public, dimension(:,:), allocatable :: a_cent
real(kind=double), public, dimension(:,:), allocatable :: d_tedge
real(kind=double), public, dimension(:,:), allocatable :: d_redge
real(kind=double), public, dimension(:,:), allocatable :: d_cent
integer, public, dimension(:), allocatable :: a_shape
integer, public, dimension(:), allocatable :: d_shape
character(len=20), public :: system = ''
real(kind=double), public, dimension(3) :: xyz_a_tedge
real(kind=double), public, dimension(3) :: xyz_a_redge
real(kind=double), public, dimension(3) :: xyz_a_cent
real(kind=double), public, dimension(3) :: xyz_d_tedge
real(kind=double), public, dimension(3) :: xyz_d_redge
real(kind=double), public, dimension(3) :: xyz_d_cent
real(kind=double), public, dimension(3) :: eff_rd
real(kind=double), public, dimension(3) :: rd
real(kind=double), public, dimension(3) :: rd_d
real(kind=double), public, dimension(3) :: r0
real(kind=double), public, dimension(3) :: r0_d
real(kind=double), public, dimension(3) :: v0
real(kind=double), public, dimension(3,3) :: basis
real(kind=double), public, dimension(3,3) :: inv_basis
real(kind=double), public, dimension(50) :: xd
real(kind=double), public, dimension(50) :: yd
real(kind=double), public, dimension(:,:,:,:,:), allocatable :: effrd
real(kind=double), public, dimension(:,:,:,:), allocatable :: phit
real(kind=double), public :: total_prob
real(kind=double), public :: hh
real(kind=double), public :: hw
real(kind=double), public :: dprob
real(kind=double), public :: dx
real(kind=double), public :: dy
real(kind=double), public :: r
integer, public :: ichan
integer, public :: i
integer, public :: j
integer, public :: k
integer, public :: ix
integer, public :: iy
integer, public :: d_index
integer, public :: nd
integer, public :: cnt
integer, public :: error
Call graph
read_npa calls h5fclose_f, h5gclose_f, uvw_to_xyz, h5open_f, h5close_f, h5ltread_dataset_int_scalar_f, h5ltpath_valid_f, h5ltread_dataset_int_f, h5ltread_dataset_string_f, h5fopen_f, xyz_to_uvw, h5gopen_f, normp, plane_basis, h5ltread_dataset_double_f, hit_npa_detector
h5ltread_dataset_int_scalar_f calls h5ltread_dataset_int_f
plane_basis calls normp, cross_product
hit_npa_detector calls in_boundary, plane_intercept
fidasim calls read_npa