rng_uniform – Fortran Program
rng_uniform Function
Source File
public function rng_uniform(self) result(u)
Arguments
Type Intent Optional Attributes Name
type(rng_type), intent(inout) :: self
Random Number Generator
Return Value real(kind=Float64)
Uniform random deviate
Description
Generate a uniformally-distributed random number in the range [0,1)
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: ix
integer, public :: iy
integer, public :: k
Call graph
randu calls rng_uniform
rng_normal calls rng_uniform
randind_w_2 calls randu
get_nlaunch calls randu
fida_mc calls randu, get_beam_cx_prob
randind_w_1 calls randu
mc_fastion calls randu, randind
randind_n calls randu
bremsstrahlung calls randu
read_chords calls randu
mc_nbi calls randu, randn
ndmc calls randu, mc_nbi, randind
fida_weights_mc calls randu, get_nlaunch, randind, get_beam_cx_prob
npa_mc calls randu, get_beam_cx_prob
mc_halo calls randu, randn
randind calls randind_w_2, randind_w_1, randind_n
fida_f calls get_nlaunch, mc_fastion, get_beam_cx_prob
halo calls get_nlaunch, mc_halo, get_beam_cx_prob
dcx calls get_nlaunch, mc_halo, get_beam_cx_prob
npa_f calls get_nlaunch, mc_fastion, get_beam_cx_prob
fidasim calls fida_mc, bremsstrahlung, read_chords, ndmc, fida_weights_mc, npa_mc, fida_f, halo, dcx, npa_f, fida_weights_los, npa_weights
fida_weights_los calls mc_halo
get_beam_cx_prob calls mc_halo
npa_weights calls get_beam_cx_prob
randn calls rng_normal