store_fw_photons – Fortran Program
store_fw_photons Subroutine
Source File
public subroutine store_fw_photons(eind, pind, pos, vi, denf, photons)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: eind
integer, intent(in) :: pind
real(kind=double), intent(in), dimension(3) :: pos
real(kind=double), intent(in), dimension(3) :: vi
real(kind=double), intent(in) :: denf
real(kind=double), intent(in) :: photons
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=double), public :: dlength
real(kind=double), public :: sigma_pi
type(LocalEMFields), public :: fields
integer(kind=long), public, dimension(3) :: ind
real(kind=double), public, dimension(3) :: vp
integer, public :: ichan
Call graph
store_fw_photons calls get_indices, store_fw_photons_at_chan, get_fields
store_fw_photons_at_chan calls spectrum
get_fields calls normp, in_plasma, interpol_coeff, calc_perp_vectors, xyz_to_uvw, get_position
spectrum calls normp
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
calc_perp_vectors calls normp
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
fida_weights_mc calls store_fw_photons
fidasim calls fida_weights_mc