store_fida_photons – Fortran Program
store_fida_photons Subroutine
Source File
public subroutine store_fida_photons(pos, vi, photons, orbit_class)
Arguments
Type Intent Optional Attributes Name
real(kind=double), intent(in), dimension(3) :: pos
real(kind=double), intent(in), dimension(3) :: vi
real(kind=double), intent(in) :: photons
integer, intent(in), optional :: orbit_class
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=double), public, dimension(n_stark) :: lambda
real(kind=double), public, dimension(n_stark) :: intensity
real(kind=double), public :: dlength
real(kind=double), public :: sigma_pi
type(LocalEMFields), public :: fields
integer(kind=long), public, dimension(3) :: ind
real(kind=double), public, dimension(3) :: vp
integer, public :: ichan
integer, public :: i
integer, public :: bin
integer, public :: iclass
Call graph
store_fida_photons calls get_indices, spectrum, get_fields
spectrum calls normp
get_fields calls normp, in_plasma, interpol_coeff, calc_perp_vectors, xyz_to_uvw, get_position
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
calc_perp_vectors calls normp
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
fida_f calls store_fida_photons
fida_mc calls store_fida_photons
fidasim calls fida_f, fida_mc