write_bb_H_H – Fortran Program
write_bb_H_H Subroutine
Source File
public subroutine write_bb_H_H(id, namelist_file, n_max, m_max)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(inout) :: id
character(len=*), intent(in) :: namelist_file
integer, intent(in) :: n_max
integer, intent(in) :: m_max
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=Float64), public :: emin
real(kind=Float64), public :: emax
integer, public :: nenergy
real(kind=Float64), public :: eb
real(kind=Float64), public :: dlogE
real(kind=Float64), public, dimension(:), allocatable :: ebarr
real(kind=Float64), public, dimension(:,:), allocatable :: ioniz
real(kind=Float64), public, dimension(:,:,:), allocatable :: cx
real(kind=Float64), public, dimension(:,:,:), allocatable :: excit
integer(kind=HID_T), public :: gid
integer(kind=HSIZE_T), public, dimension(1) :: dim1
integer(kind=HSIZE_T), public, dimension(2) :: dim2
integer(kind=HSIZE_T), public, dimension(3) :: dim3
integer, public :: i
integer, public :: cnt
integer, public :: error
logical, public :: exis
Call graph
write_bb_h_h calls h5ltmake_dataset_int_f, h5gcreate_f, p_ioniz, h5gclose_f, h5ltmake_compressed_dataset_double_f, p_cx, p_excit, h5ltmake_dataset_double_f, h5ltset_attribute_string_f
p_ioniz calls p_ioniz_n
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6
p_cx calls p_cx_n
p_excit calls p_excit_n
p_ioniz_n calls p_ioniz_1_omullane, p_ioniz_3_omullane, p_ioniz_4_omullane, p_ioniz_2_omullane, p_ioniz_5_omullane
h5ltmake_compressed_dataset_double_f_4 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_7 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_3 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_1 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_2 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_5 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_6 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
p_cx_n calls p_cx_2, p_cx_janev, p_cx_1_4_adas, p_cx_3_4_adas, p_cx_3_5_adas, p_cx_1, m_spread, p_cx_3
p_cx_2 calls p_cx_janev, m_spread, p_cx_1_2_adas, p_cx_2_2_adas, p_cx_2_3_adas
p_cx_janev calls p_cx_2_janev, p_cx_4_janev, p_cx_3_janev, p_cx_1_janev
p_cx_1 calls p_cx_janev, p_cx_1_4_adas, p_cx_1_2_adas, p_cx_1_3_adas, p_cx_1_1_adas
p_cx_3 calls p_cx_janev, p_cx_3_4_adas, p_cx_3_5_adas, p_cx_1, m_spread, p_cx_1_3_adas, p_cx_3_3_adas, p_cx_3_6inf_adas, p_cx_3_2_adas
p_excit_n calls p_excit_2_janev, p_excit_3_janev, p_excit_1_janev
p_excit_2_janev calls p_excit_2_5_janev, p_excit_2_8_janev, p_excit_2_3_janev, p_excit_2_7_janev, p_excit_2_10_janev, p_excit_2_4_janev, p_excit_2_6_janev, p_excit_2_9_janev
p_excit_3_janev calls p_excit_3_10_janev, p_excit_3_4_janev, p_excit_3_9_janev, p_excit_3_7_janev, p_excit_3_6_janev, p_excit_3_8_janev, p_excit_3_5_janev
p_excit_1_janev calls p_excit_1_5_janev, p_excit_1_4_janev, p_excit_1_2_janev, p_excit_1_3_janev, p_excit_1_6_janev
p_excit_2_8_janev calls p_excit_2_5_janev
p_excit_2_7_janev calls p_excit_2_5_janev
p_excit_2_10_janev calls p_excit_2_5_janev
p_excit_2_6_janev calls p_excit_2_5_janev
p_excit_2_9_janev calls p_excit_2_5_janev
p_excit_3_10_janev calls p_excit_3_6_janev
p_excit_3_9_janev calls p_excit_3_6_janev
p_excit_3_7_janev calls p_excit_3_6_janev
p_excit_3_8_janev calls p_excit_3_6_janev
generate_tables calls write_bb_h_h