write_birth_profile – Fortran Program
write_birth_profile Subroutine
Source File
public subroutine write_birth_profile()
Arguments
None
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=HID_T), public :: fid
integer(kind=HSIZE_T), public, dimension(4) :: dim4
integer(kind=HSIZE_T), public, dimension(2) :: dim2
integer(kind=HSIZE_T), public, dimension(1) :: d
integer, public :: error
integer, public :: i
character(len=120), public :: filename
real(kind=double), public, dimension(:,:), allocatable :: ri
real(kind=double), public, dimension(:,:), allocatable :: vi
real(kind=double), public, dimension(3) :: xyz
real(kind=double), public, dimension(3) :: uvw
real(kind=double), public, dimension(3) :: v_uvw
Call graph
write_birth_profile calls h5fcreate_f, h5ltmake_dataset_int_f, h5fclose_f, h5open_f, h5close_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, write_beam_grid, xyz_to_uvw
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6
write_beam_grid calls h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, xyz_to_uvw, h5gcreate_f, h5gclose_f
h5ltmake_compressed_dataset_double_f_4 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_7 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_3 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_1 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_2 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_5 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_6 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
fidasim calls write_birth_profile