write_einstein – Fortran Program
write_einstein Subroutine
Source File
public subroutine write_einstein(id, n_max, m_max)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(inout) :: id
integer, intent(in) :: n_max
integer, intent(in) :: m_max
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=Float64), public, dimension(n_max,m_max) :: ein
integer(kind=HID_T), public :: gid
integer(kind=HSIZE_T), public, dimension(1) :: dim1
integer(kind=HSIZE_T), public, dimension(2) :: dim2
integer, public :: error
Call graph
write_einstein calls h5gcreate_f, h5gclose_f, h5ltset_attribute_string_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6
h5ltmake_compressed_dataset_double_f_4 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_7 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_3 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_1 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_2 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_5 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_6 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
generate_tables calls write_einstein