write_bb_H_Aq – Fortran Program
write_bb_H_Aq Subroutine
Source File
public subroutine write_bb_H_Aq(id, namelist_file, n_max, m_max)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(inout) :: id
character(len=*), intent(in) :: namelist_file
integer, intent(in) :: n_max
integer, intent(in) :: m_max
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: q
real(kind=Float64), public :: emin
real(kind=Float64), public :: emax
integer, public :: nenergy
real(kind=Float64), public :: eb
real(kind=Float64), public :: dlogE
real(kind=Float64), public, dimension(:), allocatable :: ebarr
real(kind=Float64), public, dimension(:,:), allocatable :: cx
real(kind=Float64), public, dimension(:,:), allocatable :: ioniz
real(kind=Float64), public, dimension(:,:,:), allocatable :: excit
integer(kind=HID_T), public :: gid
integer(kind=HSIZE_T), public, dimension(1) :: dim1
integer(kind=HSIZE_T), public, dimension(2) :: dim2
integer(kind=HSIZE_T), public, dimension(3) :: dim3
character(len=10), public :: aname
character(len=5), public :: asym
integer, public :: i
integer, public :: cnt
integer, public :: error
logical, public :: exis
Call graph
write_bb_h_aq calls h5ltmake_dataset_int_f, h5gcreate_f, aq_cx, h5gclose_f, h5ltmake_compressed_dataset_double_f, aq_excit, h5ltmake_dataset_double_f, h5ltset_attribute_string_f, aq_ioniz
aq_cx calls aq_cx_n
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6
aq_excit calls aq_excit_n
aq_ioniz calls aq_ioniz_n
aq_cx_n calls aq_cx_n_adas, aq_cx_n_janev
aq_cx_n_adas calls c6_cx_2_adas, c6_cx_3_adas, b5_cx_1_adas, c6_cx_1_adas, b5_cx_2_adas
aq_cx_n_janev calls c6_cx_1_janev, b5_cx_1_janev
h5ltmake_compressed_dataset_double_f_4 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_7 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_3 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_1 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_2 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_5 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_6 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
aq_excit_n calls aq_excit_2_janev, aq_excit_3_janev, aq_excit_1_janev, aq_excit_n_janev
aq_excit_2_janev calls aq_excit_2_10_janev, aq_excit_2_6_janev, aq_excit_2_8_janev, aq_excit_2_9_janev, aq_excit_2_5_janev, aq_excit_2_4_janev, aq_excit_2_3_janev, aq_excit_2_7_janev
aq_excit_3_janev calls aq_excit_3_4_janev, aq_excit_3_6_janev, aq_excit_3_10_janev, aq_excit_3_8_janev, aq_excit_3_9_janev, aq_excit_3_7_janev, aq_excit_3_5_janev
aq_excit_1_janev calls aq_excit_1_3_janev, aq_excit_1_4_janev, aq_excit_1_5_janev, aq_excit_1_2_janev
aq_excit_2_10_janev calls aq_excit_2_5_janev
aq_excit_2_6_janev calls aq_excit_2_5_janev
aq_excit_2_8_janev calls aq_excit_2_5_janev
aq_excit_2_9_janev calls aq_excit_2_5_janev
aq_excit_2_7_janev calls aq_excit_2_5_janev
aq_excit_3_10_janev calls aq_excit_3_6_janev
aq_excit_3_8_janev calls aq_excit_3_6_janev
aq_excit_3_9_janev calls aq_excit_3_6_janev
aq_excit_3_7_janev calls aq_excit_3_6_janev
aq_ioniz_n calls b5_ioniz_1_janev, c6_ioniz_1_janev, aq_ioniz_n_janev
generate_tables calls write_bb_h_aq