write_bt_H_Aq – Fortran Program
write_bt_H_Aq Subroutine
Source File
public subroutine write_bt_H_Aq(id, namelist_file, n_max, m_max)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(inout) :: id
character(len=*), intent(in) :: namelist_file
integer, intent(in) :: n_max
integer, intent(in) :: m_max
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: q
real(kind=Float64), public :: mass
real(kind=Float64), public :: emin
real(kind=Float64), public :: emax
integer, public :: nenergy
real(kind=Float64), public :: tmin
real(kind=Float64), public :: tmax
integer, public :: ntemp
real(kind=Float64), public :: eb
real(kind=Float64), public :: dlogE
real(kind=Float64), public, dimension(:), allocatable :: ebarr
real(kind=Float64), public :: ti
real(kind=Float64), public :: dlogT
real(kind=Float64), public, dimension(:), allocatable :: tarr
real(kind=Float64), public, dimension(:,:,:,:), allocatable :: ioniz
real(kind=Float64), public, dimension(:,:,:,:), allocatable :: cx
real(kind=Float64), public, dimension(:,:,:,:,:), allocatable :: excit
integer(kind=HID_T), public :: gid
integer(kind=HSIZE_T), public, dimension(1) :: dim1
integer(kind=HSIZE_T), public, dimension(2) :: dim2
integer(kind=HSIZE_T), public, dimension(3) :: dim3
integer(kind=HSIZE_T), public, dimension(4) :: dim4
integer(kind=HSIZE_T), public, dimension(5) :: dim5
integer, public :: ie
integer, public :: it
integer, public :: ia
integer, public :: n
integer, public :: m
integer, public :: error
integer, public :: cnt
real(kind=Float64), public :: rate
integer, public, parameter :: n_bt_amu = 2
real(kind=Float64), public, dimension(2,n_bt_amu) :: a
character(len=10), public :: aname
character(len=5), public :: asym
logical, public :: exis
Call graph
write_bt_h_aq calls h5ltmake_dataset_int_f, h5gcreate_f, h5gclose_f, h5ltmake_compressed_dataset_double_f, bt_maxwellian, h5ltmake_dataset_double_f, h5ltset_attribute_string_f
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6
bt_maxwellian calls bt_maxwellian_q_n, bt_maxwellian_n_m, bt_maxwellian_n, bt_maxwellian_q_n_m
h5ltmake_compressed_dataset_double_f_4 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_7 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_3 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_1 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_2 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_5 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_6 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
bt_maxwellian_q_n calls simpsons_rule
bt_maxwellian_n_m calls simpsons_rule
bt_maxwellian_n calls simpsons_rule
bt_maxwellian_q_n_m calls simpsons_rule
generate_tables calls write_bt_h_aq