xyz_to_uvw – Fortran Program
xyz_to_uvw Subroutine
Source File
public subroutine xyz_to_uvw(xyz, uvw)
Arguments
Type Intent Optional Attributes Name
real(kind=double), intent(in), dimension(3) :: xyz
real(kind=double), intent(out), dimension(3) :: uvw
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=double), public, dimension(3) :: origin
real(kind=double), public, dimension(3,3) :: basis
Call graph
in_plasma calls xyz_to_uvw
write_birth_profile calls xyz_to_uvw, write_beam_grid
get_fields calls xyz_to_uvw, in_plasma
get_plasma calls xyz_to_uvw, in_plasma
get_ep_denf calls xyz_to_uvw, in_plasma
store_npa calls xyz_to_uvw, get_fields
write_beam_grid calls xyz_to_uvw
read_npa calls xyz_to_uvw
get_distribution calls xyz_to_uvw, in_plasma
track calls in_plasma
fida_weights_los calls get_fields, get_plasma, get_ep_denf, track, mc_halo
fida_mc calls get_fields, get_plasma, track, store_fida_photons, get_beam_cx_prob
fida_f calls get_plasma, track, mc_fastion, store_fida_photons, get_beam_cx_prob
halo calls get_plasma, track, store_bes_photons, mc_halo, get_beam_cx_prob
read_chords calls track
ndmc calls get_plasma, track, store_bes_photons
fida_weights_mc calls get_fields, get_plasma, get_ep_denf, track, store_fw_photons, get_beam_cx_prob
dcx calls get_plasma, track, store_bes_photons, mc_halo, get_beam_cx_prob
fidasim calls write_birth_profile, read_npa, fida_weights_los, fida_mc, fida_f, halo, read_chords, ndmc, fida_weights_mc, dcx, npa_weights, npa_mc, npa_f, bremsstrahlung, write_neutrals, write_dcx
store_fw_photons calls get_fields
store_bes_photons calls get_fields
mc_fastion calls get_fields, get_distribution
npa_weights calls get_fields, get_ep_denf, attenuate, get_beam_cx_prob, write_npa_weights
store_fida_photons calls get_fields
npa_mc calls get_fields, get_plasma, store_npa, attenuate, get_beam_cx_prob
npa_f calls get_plasma, store_npa, mc_fastion, attenuate, get_beam_cx_prob
bremsstrahlung calls get_plasma
attenuate calls get_plasma
mc_halo calls get_plasma
get_beam_cx_prob calls mc_halo
write_npa_weights calls write_beam_grid
write_neutrals calls write_beam_grid
write_dcx calls write_beam_grid