h5ltmake_compressed_dataset_double_f – Fortran Program
h5ltmake_compressed_dataset_double_f Interface
Source File
public interface h5ltmake_compressed_dataset_double_f
Write a compressed datasets of 64-bit floats
Calls
Called By
Module Procedures
public subroutine h5ltmake_compressed_dataset_double_f_1(loc_id, dset_name, rank, dims, buf, error)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: loc_id
HDF5 file or group identifier
character(len=*), intent(in) :: dset_name
Name of the dataset to create
integer, intent(in) :: rank
Number of dimensions of dataspace
integer(kind=HSIZE_T), intent(in), dimension(*) :: dims
Array of the size of each dimension
real(kind=double), intent(in), dimension(dims(1)) :: buf
Buffer with data to be written to the dataset
integer, intent(out) :: error
HDF5 error code
Description
Write a compressed 64-bit float dataset of dimension 1
public subroutine h5ltmake_compressed_dataset_double_f_2(loc_id, dset_name, rank, dims, buf, error)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: loc_id
HDF5 file or group identifier
character(len=*), intent(in) :: dset_name
Name of the dataset to create
integer, intent(in) :: rank
Number of dimensions of dataspace
integer(kind=HSIZE_T), intent(in), dimension(*) :: dims
Array of the size of each dimension
real(kind=double), intent(in), dimension(dims(1),dims(2)) :: buf
Buffer with data to be written to the dataset
integer, intent(out) :: error
HDF5 error code
Description
Write a compressed 64-bit float dataset of dimension 2
public subroutine h5ltmake_compressed_dataset_double_f_3(loc_id, dset_name, rank, dims, buf, error)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: loc_id
HDF5 file or group identifier
character(len=*), intent(in) :: dset_name
Name of the dataset to create
integer, intent(in) :: rank
Number of dimensions of dataspace
integer(kind=HSIZE_T), intent(in), dimension(*) :: dims
Array of the size of each dimension
real(kind=double), intent(in), dimension(dims(1),dims(2),dims(3)) :: buf
Buffer with data to be written to the dataset
integer, intent(out) :: error
HDF5 error code
Description
Write a compressed 64-bit float dataset of dimension 3
public subroutine h5ltmake_compressed_dataset_double_f_4(loc_id, dset_name, rank, dims, buf, error)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: loc_id
HDF5 file or group identifier
character(len=*), intent(in) :: dset_name
Name of the dataset to create
integer, intent(in) :: rank
Number of dimensions of dataspace
integer(kind=HSIZE_T), intent(in), dimension(*) :: dims
Array of the size of each dimension
real(kind=double), intent(in), dimension(dims(1),dims(2),dims(3),dims(4)) :: buf
Buffer with data to be written to the dataset
integer, intent(out) :: error
HDF5 error code
Description
Write a compressed 64-bit float dataset of dimension 4
public subroutine h5ltmake_compressed_dataset_double_f_5(loc_id, dset_name, rank, dims, buf, error)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: loc_id
HDF5 file or group identifier
character(len=*), intent(in) :: dset_name
Name of the dataset to create
integer, intent(in) :: rank
Number of dimensions of dataspace
integer(kind=HSIZE_T), intent(in), dimension(*) :: dims
Array of the size of each dimension
real(kind=double), intent(in), dimension(dims(1),dims(2),dims(3),dims(4),dims(5)) :: buf
Buffer with data to be written to the dataset
integer, intent(out) :: error
HDF5 error code
Description
Write a compressed 64-bit float dataset of dimension 5
public subroutine h5ltmake_compressed_dataset_double_f_6(loc_id, dset_name, rank, dims, buf, error)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: loc_id
HDF5 file or group identifier
character(len=*), intent(in) :: dset_name
Name of the dataset to create
integer, intent(in) :: rank
Number of dimensions of dataspace
integer(kind=HSIZE_T), intent(in), dimension(*) :: dims
Array of the size of each dimension
real(kind=double), intent(in), dimension(dims(1),dims(2),dims(3),dims(4),dims(5),dims(6)) :: buf
Buffer with data to be written to the dataset
integer, intent(out) :: error
HDF5 error code
Description
Write a compressed 64-bit float dataset of dimension 6
public subroutine h5ltmake_compressed_dataset_double_f_7(loc_id, dset_name, rank, dims, buf, error)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: loc_id
HDF5 file or group identifier
character(len=*), intent(in) :: dset_name
Name of the dataset to create
integer, intent(in) :: rank
Number of dimensions of dataspace
integer(kind=HSIZE_T), intent(in), dimension(*) :: dims
Array of the size of each dimension
real(kind=double), intent(in), dimension(dims(1),dims(2),dims(3),dims(4),dims(5),dims(6),dims(7)) :: buf
Buffer with data to be written to the dataset
integer, intent(out) :: error
HDF5 error code
Description
Write a compressed 64-bit float dataset of dimension 7
Call graph
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6
h5ltmake_compressed_dataset_double_f_4 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_7 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_3 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_1 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_2 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_5 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_6 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
write_bt_h_h calls h5ltmake_compressed_dataset_double_f
write_birth_profile calls h5ltmake_compressed_dataset_double_f, write_beam_grid
write_fida_weights calls h5ltmake_compressed_dataset_double_f
write_bb_h_aq calls h5ltmake_compressed_dataset_double_f
write_neutrals calls h5ltmake_compressed_dataset_double_f, write_beam_grid
write_bt_h_aq calls h5ltmake_compressed_dataset_double_f
write_beam_grid calls h5ltmake_compressed_dataset_double_f
write_npa_weights calls h5ltmake_compressed_dataset_double_f, write_beam_grid
write_bb_h_h calls h5ltmake_compressed_dataset_double_f
write_dcx calls h5ltmake_compressed_dataset_double_f, write_beam_grid
write_bb_h_e calls h5ltmake_compressed_dataset_double_f
write_spectra calls h5ltmake_compressed_dataset_double_f
write_einstein calls h5ltmake_compressed_dataset_double_f
write_bt_h_e calls h5ltmake_compressed_dataset_double_f
write_npa calls h5ltmake_compressed_dataset_double_f
generate_tables calls write_bt_h_h, write_bb_h_aq, write_bt_h_aq, write_bb_h_h, write_bb_h_e, write_einstein, write_bt_h_e
fidasim calls write_birth_profile, write_neutrals, write_dcx, write_spectra, write_npa, fida_weights_los, fida_weights_mc, npa_weights
fida_weights_los calls write_fida_weights
fida_weights_mc calls write_fida_weights
npa_weights calls write_npa_weights