fidasim – Fortran Program
fidasim Program
Source File
Uses:
simulation
hdf5_extra
omp_lib
Calls
Variables
Type Attributes Name Initial
character(len=3) :: arg = ''
integer, dimension(8) :: time_arr
integer, dimension(8) :: time_start
integer, dimension(8) :: time_end
integer :: i
integer :: narg
integer :: nthreads
integer :: max_threads
integer :: hour
integer :: minu
integer :: sec
Call graph
fidasim calls read_equilibrium, halo, npa_f, make_beam_grid, rng_init, ndmc, check_compression_availability, read_npa, npa_mc, dcx, fida_mc, fida_f, read_neutrals, write_dcx, npa_weights, fida_weights_mc, write_npa, read_tables, fida_weights_los, read_distribution, write_neutrals, bremsstrahlung, read_inputs, write_spectra, read_beam, print_banner, omp_get_num_procs, write_birth_profile, omp_set_num_threads, read_chords
read_equilibrium calls h5fclose_f, h5gclose_f, h5open_f, h5close_f, h5ltread_dataset_int_scalar_f, h5ltread_dataset_int_f, h5fopen_f, h5gopen_f, h5ltread_dataset_double_f
halo calls get_nlaunch, store_neutrals, get_plasma, colrad, store_bes_photons, track, get_beam_cx_prob, mc_halo
npa_f calls get_nlaunch, get_plasma, get_beam_cx_prob, mc_fastion, store_npa, attenuate, hit_npa_detector
make_beam_grid calls tb_zyx
ndmc calls store_neutrals, get_plasma, colrad, store_bes_photons, track, randu, randind, store_births, mc_nbi
check_compression_availability calls h5open_f, h5close_f, h5zget_filter_info_f, h5zfilter_avail_f
read_npa calls h5fclose_f, h5gclose_f, h5open_f, h5close_f, h5ltread_dataset_int_scalar_f, h5ltread_dataset_int_f, h5fopen_f, h5gopen_f, h5ltread_dataset_double_f, xyz_to_uvw, normp, hit_npa_detector, uvw_to_xyz, h5ltpath_valid_f, h5ltread_dataset_string_f, plane_basis
npa_mc calls get_plasma, get_beam_cx_prob, randu, get_indices, get_fields, store_npa, attenuate, hit_npa_detector, pitch_to_vec, gyro_correction, uvw_to_xyz
dcx calls get_nlaunch, store_neutrals, get_plasma, colrad, store_bes_photons, track, get_beam_cx_prob, mc_halo
fida_mc calls get_plasma, colrad, track, get_beam_cx_prob, randu, get_fields, pitch_to_vec, gyro_correction, uvw_to_xyz, store_fida_photons
fida_f calls get_nlaunch, get_plasma, colrad, track, get_beam_cx_prob, mc_fastion, store_fida_photons
read_neutrals calls h5fclose_f, h5gclose_f, h5open_f, h5close_f, h5ltread_dataset_int_scalar_f, h5fopen_f, h5gopen_f, h5ltread_dataset_double_f
write_dcx calls h5fclose_f, h5open_f, h5close_f, h5fcreate_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, write_beam_grid, h5ltset_attribute_string_f
npa_weights calls get_beam_cx_prob, get_fields, normp, attenuate, hit_npa_detector, gyro_correction, get_ep_denf, write_npa_weights
fida_weights_mc calls get_nlaunch, get_plasma, colrad, track, get_beam_cx_prob, randu, get_fields, pitch_to_vec, gyro_correction, randind, get_ep_denf, write_fida_weights, store_fw_photons
write_npa calls h5fclose_f, h5gclose_f, h5open_f, h5close_f, h5fcreate_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, h5gcreate_f, h5ltmake_compressed_dataset_int_f
read_tables calls h5fclose_f, h5open_f, h5close_f, h5ltread_dataset_int_scalar_f, h5fopen_f, h5ltread_dataset_double_f, read_cross, read_rates
fida_weights_los calls get_plasma, colrad, track, mc_halo, get_fields, normp, calc_perp_vectors, neut_rates, pitch_to_vec, grid_intersect, get_ep_denf, write_fida_weights, store_fw_photons_at_chan
read_distribution calls h5fclose_f, h5open_f, h5close_f, h5ltread_dataset_int_scalar_f, h5fopen_f, read_f, read_mc
write_neutrals calls h5fclose_f, h5open_f, h5close_f, h5fcreate_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, write_beam_grid, h5ltset_attribute_string_f
bremsstrahlung calls get_plasma, randu, normp, line_basis
write_spectra calls h5fclose_f, h5open_f, h5close_f, h5fcreate_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f
read_beam calls h5fclose_f, h5gclose_f, h5open_f, h5close_f, h5ltread_dataset_int_scalar_f, h5fopen_f, h5gopen_f, h5ltread_dataset_double_f, tb_zyx, uvw_to_xyz, h5ltread_dataset_string_f, h5ltread_dataset_double_scalar_f
write_birth_profile calls h5fclose_f, h5open_f, h5close_f, xyz_to_uvw, h5fcreate_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, write_beam_grid, h5ltset_attribute_string_f
read_chords calls h5fclose_f, h5gclose_f, h5open_f, h5close_f, h5ltread_dataset_int_scalar_f, h5fopen_f, h5gopen_f, h5ltread_dataset_double_f, track, randu, normp, grid_intersect, uvw_to_xyz, h5ltpath_valid_f, h5ltread_dataset_string_f, line_basis
h5ltread_dataset_int_scalar_f calls h5ltread_dataset_int_f
get_nlaunch calls randu
get_plasma calls in_plasma, interpol_coeff, xyz_to_uvw, get_position
colrad calls matinv, get_rate_matrix, eigen
store_bes_photons calls get_indices, spectrum, get_fields
track calls in_plasma, get_indices
get_beam_cx_prob calls mc_halo, normp, neut_rates
mc_halo calls get_plasma, randu, randn
randu calls rng_uniform, omp_get_thread_num
in_plasma calls xyz_to_uvw, interpol
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol calls interpol2d_2d_arr, interpol1d_arr, interpol2d_arr
interpol2d_2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
matinv calls ludcmp, lubksb
get_rate_matrix calls interpol_coeff
eigen calls balance, elmtrans, elmhes, balback, hqr2
ludcmp calls swap, outerprod
balance calls rswap
elmhes calls rswap
balback calls rswap
hqr2 calls hqrvec
hqrvec calls comdiv
spectrum calls normp
get_fields calls in_plasma, interpol_coeff, xyz_to_uvw, get_position, normp, calc_perp_vectors
calc_perp_vectors calls normp
neut_rates calls interpol_coeff, normp
randn calls omp_get_thread_num, rng_normal
rng_normal calls rng_uniform
mc_fastion calls randu, get_fields, pitch_to_vec, gyro_correction, randind, get_distribution
store_npa calls xyz_to_uvw, get_fields, normp
attenuate calls get_plasma, colrad, normp
hit_npa_detector calls in_boundary, plane_intercept
gyro_correction calls cross_product
randind calls randind_w_2, randind_w_1, randind_n
get_distribution calls in_plasma, xyz_to_uvw, get_position, interpol
randind_w_2 calls randu, ind2sub
randind_w_1 calls randu
randind_n calls randu
mc_nbi calls randu, normp, randn, grid_intersect
plane_basis calls normp, cross_product
store_fida_photons calls get_indices, spectrum, get_fields
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6
write_beam_grid calls h5gclose_f, xyz_to_uvw, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, h5gcreate_f
h5ltmake_compressed_dataset_double_f_4 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_7 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_3 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_1 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_2 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_5 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_6 calls h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5ltmake_dataset_double_f, h5pcreate_f, h5pset_chunk_f
get_ep_denf calls in_plasma, xyz_to_uvw, get_position, interpol
write_npa_weights calls h5fclose_f, h5open_f, h5close_f, h5fcreate_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, write_beam_grid, h5ltset_attribute_string_f
write_fida_weights calls h5fclose_f, h5open_f, h5close_f, h5fcreate_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f
store_fw_photons calls get_indices, get_fields, store_fw_photons_at_chan
store_fw_photons_at_chan calls spectrum
h5ltmake_compressed_dataset_int_f calls h5ltmake_compressed_dataset_int_f_3, h5ltmake_compressed_dataset_int_f_6, h5ltmake_compressed_dataset_int_f_7, h5ltmake_compressed_dataset_int_f_5, h5ltmake_compressed_dataset_int_f_1, h5ltmake_compressed_dataset_int_f_2, h5ltmake_compressed_dataset_int_f_4
h5ltmake_compressed_dataset_int_f_3 calls h5ltmake_dataset_int_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_int_f_6 calls h5ltmake_dataset_int_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_int_f_7 calls h5ltmake_dataset_int_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_int_f_5 calls h5ltmake_dataset_int_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_int_f_1 calls h5ltmake_dataset_int_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_int_f_2 calls h5ltmake_dataset_int_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_int_f_4 calls h5ltmake_dataset_int_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
read_cross calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5ltread_dataset_double_scalar_f
read_rates calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, normp, h5ltpath_valid_f, h5ltread_dataset_double_scalar_f, h5ltget_dataset_ndims_f
h5ltread_dataset_double_scalar_f calls h5ltread_dataset_double_f
read_f calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f
read_mc calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_int_f, h5ltread_dataset_double_f, uvw_to_xyz
line_basis calls tb_zyx