generate_tables – Fortran Program
generate_tables Program
Source File
Uses:
atomic_tables
H5LT
HDF5
hdf5_extra
omp_lib
Calls
Variables
Type Attributes Name Initial
character(len=200) :: namelist_file
character(len=3) :: arg
character(len=200) :: tables_file = ''
integer :: n_max
integer :: m_max
integer, dimension(8) :: time_arr
integer, dimension(8) :: time_start
integer, dimension(8) :: time_end
integer :: hour
integer :: minu
integer :: sec
integer :: argc
integer :: max_threads
integer :: nthreads
integer(kind=HID_T) :: fid
integer(kind=HID_T) :: gid
integer :: error
logical :: exis
Call graph
generate_tables calls write_bt_h_h, h5fcreate_f, omp_get_num_procs, write_bb_h_e, h5gcreate_f, write_bb_h_aq, h5open_f, h5gclose_f, h5fclose_f, h5close_f, omp_set_num_threads, write_bt_h_aq, write_bb_h_h, check_compression_availability, h5ltset_attribute_string_f, write_einstein, write_bt_h_e
write_bt_h_h calls h5gcreate_f, h5gclose_f, h5ltset_attribute_string_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, bt_maxwellian, h5ltmake_dataset_double_f
write_bb_h_e calls h5gcreate_f, h5gclose_f, h5ltset_attribute_string_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5ltmake_dataset_double_f, e_ioniz, e_excit
write_bb_h_aq calls h5gcreate_f, h5gclose_f, h5ltset_attribute_string_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5ltmake_dataset_double_f, aq_cx, aq_excit, aq_ioniz
write_bt_h_aq calls h5gcreate_f, h5gclose_f, h5ltset_attribute_string_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, bt_maxwellian, h5ltmake_dataset_double_f
write_bb_h_h calls h5gcreate_f, h5gclose_f, h5ltset_attribute_string_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5ltmake_dataset_double_f, p_ioniz, p_cx, p_excit
check_compression_availability calls h5open_f, h5close_f, h5zget_filter_info_f, h5zfilter_avail_f
write_einstein calls h5gcreate_f, h5gclose_f, h5ltset_attribute_string_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f
write_bt_h_e calls h5gcreate_f, h5gclose_f, h5ltset_attribute_string_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, bt_maxwellian, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6
bt_maxwellian calls bt_maxwellian_q_n, bt_maxwellian_n_m, bt_maxwellian_n, bt_maxwellian_q_n_m
h5ltmake_compressed_dataset_double_f_4 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_7 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_3 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_1 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_2 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_5 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
h5ltmake_compressed_dataset_double_f_6 calls h5ltmake_dataset_double_f, h5dclose_f, h5pset_deflate_f, h5dcreate_f, h5pclose_f, h5sclose_f, h5dwrite_f, h5pset_shuffle_f, h5screate_simple_f, h5pcreate_f, h5pset_chunk_f
bt_maxwellian_q_n calls simpsons_rule
bt_maxwellian_n_m calls simpsons_rule
bt_maxwellian_n calls simpsons_rule
bt_maxwellian_q_n_m calls simpsons_rule
e_ioniz calls e_ioniz_n
e_excit calls e_excit_n
e_ioniz_n calls e_ioniz_3_janev, e_ioniz_1_janev, e_ioniz_2_janev
e_excit_n calls e_excit_1_janev, e_excit_2_3_janev, e_excit_f
e_excit_1_janev calls e_excit_f, e_excit_1_5_janev, e_excit_1_2_janev, e_excit_1_4_janev, e_excit_1_3_janev
aq_cx calls aq_cx_n
aq_excit calls aq_excit_n
aq_ioniz calls aq_ioniz_n
aq_cx_n calls aq_cx_n_adas, aq_cx_n_janev
aq_cx_n_adas calls c6_cx_2_adas, c6_cx_3_adas, b5_cx_1_adas, c6_cx_1_adas, b5_cx_2_adas
aq_cx_n_janev calls c6_cx_1_janev, b5_cx_1_janev
aq_excit_n calls aq_excit_2_janev, aq_excit_3_janev, aq_excit_1_janev, aq_excit_n_janev
aq_excit_2_janev calls aq_excit_2_10_janev, aq_excit_2_6_janev, aq_excit_2_8_janev, aq_excit_2_9_janev, aq_excit_2_5_janev, aq_excit_2_4_janev, aq_excit_2_3_janev, aq_excit_2_7_janev
aq_excit_3_janev calls aq_excit_3_4_janev, aq_excit_3_6_janev, aq_excit_3_10_janev, aq_excit_3_8_janev, aq_excit_3_9_janev, aq_excit_3_7_janev, aq_excit_3_5_janev
aq_excit_1_janev calls aq_excit_1_3_janev, aq_excit_1_4_janev, aq_excit_1_5_janev, aq_excit_1_2_janev
aq_excit_2_10_janev calls aq_excit_2_5_janev
aq_excit_2_6_janev calls aq_excit_2_5_janev
aq_excit_2_8_janev calls aq_excit_2_5_janev
aq_excit_2_9_janev calls aq_excit_2_5_janev
aq_excit_2_7_janev calls aq_excit_2_5_janev
aq_excit_3_10_janev calls aq_excit_3_6_janev
aq_excit_3_8_janev calls aq_excit_3_6_janev
aq_excit_3_9_janev calls aq_excit_3_6_janev
aq_excit_3_7_janev calls aq_excit_3_6_janev
aq_ioniz_n calls b5_ioniz_1_janev, c6_ioniz_1_janev, aq_ioniz_n_janev
p_ioniz calls p_ioniz_n
p_cx calls p_cx_n
p_excit calls p_excit_n
p_ioniz_n calls p_ioniz_1_omullane, p_ioniz_3_omullane, p_ioniz_4_omullane, p_ioniz_2_omullane, p_ioniz_5_omullane
p_cx_n calls p_cx_2, p_cx_janev, p_cx_1_4_adas, p_cx_3_4_adas, p_cx_3_5_adas, p_cx_1, m_spread, p_cx_3
p_cx_2 calls p_cx_janev, m_spread, p_cx_1_2_adas, p_cx_2_2_adas, p_cx_2_3_adas
p_cx_janev calls p_cx_2_janev, p_cx_4_janev, p_cx_3_janev, p_cx_1_janev
p_cx_1 calls p_cx_janev, p_cx_1_4_adas, p_cx_1_2_adas, p_cx_1_3_adas, p_cx_1_1_adas
p_cx_3 calls p_cx_janev, p_cx_3_4_adas, p_cx_3_5_adas, p_cx_1, m_spread, p_cx_1_3_adas, p_cx_3_3_adas, p_cx_3_6inf_adas, p_cx_3_2_adas
p_excit_n calls p_excit_2_janev, p_excit_3_janev, p_excit_1_janev
p_excit_2_janev calls p_excit_2_5_janev, p_excit_2_8_janev, p_excit_2_3_janev, p_excit_2_7_janev, p_excit_2_10_janev, p_excit_2_4_janev, p_excit_2_6_janev, p_excit_2_9_janev
p_excit_3_janev calls p_excit_3_10_janev, p_excit_3_4_janev, p_excit_3_9_janev, p_excit_3_7_janev, p_excit_3_6_janev, p_excit_3_8_janev, p_excit_3_5_janev
p_excit_1_janev calls p_excit_1_5_janev, p_excit_1_4_janev, p_excit_1_2_janev, p_excit_1_3_janev, p_excit_1_6_janev
p_excit_2_8_janev calls p_excit_2_5_janev
p_excit_2_7_janev calls p_excit_2_5_janev
p_excit_2_10_janev calls p_excit_2_5_janev
p_excit_2_6_janev calls p_excit_2_5_janev
p_excit_2_9_janev calls p_excit_2_5_janev
p_excit_3_10_janev calls p_excit_3_6_janev
p_excit_3_9_janev calls p_excit_3_6_janev
p_excit_3_7_janev calls p_excit_3_6_janev
p_excit_3_8_janev calls p_excit_3_6_janev